// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: onvifcli.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "onvifcli.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace OnvifCli {
class OnvifCliCmdDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<OnvifCliCmd> {
  public:
  const ::OnvifCliDeviceLoginReq* loginreq_;
  const ::OnvifCliDeviceLoginResp* loginresp_;
} _OnvifCliCmd_default_instance_;

namespace protobuf_onvifcli_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnvifCliCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnvifCliCmd, _oneof_case_[0]),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnvifCliCmd, type_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_OnvifCliCmd_default_instance_), loginreq_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_OnvifCliCmd_default_instance_), loginresp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnvifCliCmd, cmd_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(OnvifCliCmd)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_OnvifCliCmd_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "onvifcli.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _OnvifCliCmd_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::protobuf_onvifclidevice_2eproto::InitDefaults();
  _OnvifCliCmd_default_instance_.DefaultConstruct();
  _OnvifCliCmd_default_instance_.loginreq_ = const_cast< ::OnvifCliDeviceLoginReq*>(
      ::OnvifCliDeviceLoginReq::internal_default_instance());
  _OnvifCliCmd_default_instance_.loginresp_ = const_cast< ::OnvifCliDeviceLoginResp*>(
      ::OnvifCliDeviceLoginResp::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016onvifcli.proto\022\010OnvifCli\032\024onvifclidevi"
      "ce.proto\"\231\001\n\013OnvifCliCmd\022\'\n\004type\030\001 \001(\0162\031"
      ".OnvifCli.OnvifCliCmdType\022+\n\010loginReq\030\002 "
      "\001(\0132\027.OnvifCliDeviceLoginReqH\000\022-\n\tloginR"
      "esp\030\003 \001(\0132\030.OnvifCliDeviceLoginRespH\000B\005\n"
      "\003cmd*^\n\017OnvifCliCmdType\022\024\n\020CLI_CMD_DEV_Z"
      "ERO\020\000\022\031\n\025CLI_CMD_DEV_LOGIN_REQ\020\001\022\032\n\026CLI_"
      "CMD_DEV_LOGIN_RESP\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 308);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "onvifcli.proto", &protobuf_RegisterTypes);
  ::protobuf_onvifclidevice_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_onvifcli_2eproto

const ::google::protobuf::EnumDescriptor* OnvifCliCmdType_descriptor() {
  protobuf_onvifcli_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_onvifcli_2eproto::file_level_enum_descriptors[0];
}
bool OnvifCliCmdType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OnvifCliCmd::kTypeFieldNumber;
const int OnvifCliCmd::kLoginReqFieldNumber;
const int OnvifCliCmd::kLoginRespFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OnvifCliCmd::OnvifCliCmd()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_onvifcli_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OnvifCli.OnvifCliCmd)
}
OnvifCliCmd::OnvifCliCmd(const OnvifCliCmd& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_ = from.type_;
  clear_has_cmd();
  switch (from.cmd_case()) {
    case kLoginReq: {
      mutable_loginreq()->::OnvifCliDeviceLoginReq::MergeFrom(from.loginreq());
      break;
    }
    case kLoginResp: {
      mutable_loginresp()->::OnvifCliDeviceLoginResp::MergeFrom(from.loginresp());
      break;
    }
    case CMD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:OnvifCli.OnvifCliCmd)
}

void OnvifCliCmd::SharedCtor() {
  type_ = 0;
  clear_has_cmd();
  _cached_size_ = 0;
}

OnvifCliCmd::~OnvifCliCmd() {
  // @@protoc_insertion_point(destructor:OnvifCli.OnvifCliCmd)
  SharedDtor();
}

void OnvifCliCmd::SharedDtor() {
  if (has_cmd()) {
    clear_cmd();
  }
}

void OnvifCliCmd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OnvifCliCmd::descriptor() {
  protobuf_onvifcli_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_onvifcli_2eproto::file_level_metadata[0].descriptor;
}

const OnvifCliCmd& OnvifCliCmd::default_instance() {
  protobuf_onvifcli_2eproto::InitDefaults();
  return *internal_default_instance();
}

OnvifCliCmd* OnvifCliCmd::New(::google::protobuf::Arena* arena) const {
  OnvifCliCmd* n = new OnvifCliCmd;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OnvifCliCmd::clear_cmd() {
// @@protoc_insertion_point(one_of_clear_start:OnvifCli.OnvifCliCmd)
  switch (cmd_case()) {
    case kLoginReq: {
      delete cmd_.loginreq_;
      break;
    }
    case kLoginResp: {
      delete cmd_.loginresp_;
      break;
    }
    case CMD_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CMD_NOT_SET;
}


void OnvifCliCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:OnvifCli.OnvifCliCmd)
  type_ = 0;
  clear_cmd();
}

bool OnvifCliCmd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OnvifCli.OnvifCliCmd)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .OnvifCli.OnvifCliCmdType type = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::OnvifCli::OnvifCliCmdType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .OnvifCliDeviceLoginReq loginReq = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_loginreq()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .OnvifCliDeviceLoginResp loginResp = 3;
      case 3: {
        if (tag == 26u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_loginresp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OnvifCli.OnvifCliCmd)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OnvifCli.OnvifCliCmd)
  return false;
#undef DO_
}

void OnvifCliCmd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OnvifCli.OnvifCliCmd)
  // .OnvifCli.OnvifCliCmdType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // .OnvifCliDeviceLoginReq loginReq = 2;
  if (has_loginreq()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *cmd_.loginreq_, output);
  }

  // .OnvifCliDeviceLoginResp loginResp = 3;
  if (has_loginresp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *cmd_.loginresp_, output);
  }

  // @@protoc_insertion_point(serialize_end:OnvifCli.OnvifCliCmd)
}

::google::protobuf::uint8* OnvifCliCmd::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OnvifCli.OnvifCliCmd)
  // .OnvifCli.OnvifCliCmdType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // .OnvifCliDeviceLoginReq loginReq = 2;
  if (has_loginreq()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *cmd_.loginreq_, false, target);
  }

  // .OnvifCliDeviceLoginResp loginResp = 3;
  if (has_loginresp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *cmd_.loginresp_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:OnvifCli.OnvifCliCmd)
  return target;
}

size_t OnvifCliCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OnvifCli.OnvifCliCmd)
  size_t total_size = 0;

  // .OnvifCli.OnvifCliCmdType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  switch (cmd_case()) {
    // .OnvifCliDeviceLoginReq loginReq = 2;
    case kLoginReq: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *cmd_.loginreq_);
      break;
    }
    // .OnvifCliDeviceLoginResp loginResp = 3;
    case kLoginResp: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *cmd_.loginresp_);
      break;
    }
    case CMD_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OnvifCliCmd::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OnvifCli.OnvifCliCmd)
  GOOGLE_DCHECK_NE(&from, this);
  const OnvifCliCmd* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OnvifCliCmd>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OnvifCli.OnvifCliCmd)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OnvifCli.OnvifCliCmd)
    MergeFrom(*source);
  }
}

void OnvifCliCmd::MergeFrom(const OnvifCliCmd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OnvifCli.OnvifCliCmd)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.type() != 0) {
    set_type(from.type());
  }
  switch (from.cmd_case()) {
    case kLoginReq: {
      mutable_loginreq()->::OnvifCliDeviceLoginReq::MergeFrom(from.loginreq());
      break;
    }
    case kLoginResp: {
      mutable_loginresp()->::OnvifCliDeviceLoginResp::MergeFrom(from.loginresp());
      break;
    }
    case CMD_NOT_SET: {
      break;
    }
  }
}

void OnvifCliCmd::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OnvifCli.OnvifCliCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OnvifCliCmd::CopyFrom(const OnvifCliCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OnvifCli.OnvifCliCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnvifCliCmd::IsInitialized() const {
  return true;
}

void OnvifCliCmd::Swap(OnvifCliCmd* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OnvifCliCmd::InternalSwap(OnvifCliCmd* other) {
  std::swap(type_, other->type_);
  std::swap(cmd_, other->cmd_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OnvifCliCmd::GetMetadata() const {
  protobuf_onvifcli_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_onvifcli_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OnvifCliCmd

// .OnvifCli.OnvifCliCmdType type = 1;
void OnvifCliCmd::clear_type() {
  type_ = 0;
}
::OnvifCli::OnvifCliCmdType OnvifCliCmd::type() const {
  // @@protoc_insertion_point(field_get:OnvifCli.OnvifCliCmd.type)
  return static_cast< ::OnvifCli::OnvifCliCmdType >(type_);
}
void OnvifCliCmd::set_type(::OnvifCli::OnvifCliCmdType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:OnvifCli.OnvifCliCmd.type)
}

// .OnvifCliDeviceLoginReq loginReq = 2;
bool OnvifCliCmd::has_loginreq() const {
  return cmd_case() == kLoginReq;
}
void OnvifCliCmd::set_has_loginreq() {
  _oneof_case_[0] = kLoginReq;
}
void OnvifCliCmd::clear_loginreq() {
  if (has_loginreq()) {
    delete cmd_.loginreq_;
    clear_has_cmd();
  }
}
 const ::OnvifCliDeviceLoginReq& OnvifCliCmd::loginreq() const {
  // @@protoc_insertion_point(field_get:OnvifCli.OnvifCliCmd.loginReq)
  return has_loginreq()
      ? *cmd_.loginreq_
      : ::OnvifCliDeviceLoginReq::default_instance();
}
::OnvifCliDeviceLoginReq* OnvifCliCmd::mutable_loginreq() {
  if (!has_loginreq()) {
    clear_cmd();
    set_has_loginreq();
    cmd_.loginreq_ = new ::OnvifCliDeviceLoginReq;
  }
  // @@protoc_insertion_point(field_mutable:OnvifCli.OnvifCliCmd.loginReq)
  return cmd_.loginreq_;
}
::OnvifCliDeviceLoginReq* OnvifCliCmd::release_loginreq() {
  // @@protoc_insertion_point(field_release:OnvifCli.OnvifCliCmd.loginReq)
  if (has_loginreq()) {
    clear_has_cmd();
    ::OnvifCliDeviceLoginReq* temp = cmd_.loginreq_;
    cmd_.loginreq_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void OnvifCliCmd::set_allocated_loginreq(::OnvifCliDeviceLoginReq* loginreq) {
  clear_cmd();
  if (loginreq) {
    set_has_loginreq();
    cmd_.loginreq_ = loginreq;
  }
  // @@protoc_insertion_point(field_set_allocated:OnvifCli.OnvifCliCmd.loginReq)
}

// .OnvifCliDeviceLoginResp loginResp = 3;
bool OnvifCliCmd::has_loginresp() const {
  return cmd_case() == kLoginResp;
}
void OnvifCliCmd::set_has_loginresp() {
  _oneof_case_[0] = kLoginResp;
}
void OnvifCliCmd::clear_loginresp() {
  if (has_loginresp()) {
    delete cmd_.loginresp_;
    clear_has_cmd();
  }
}
 const ::OnvifCliDeviceLoginResp& OnvifCliCmd::loginresp() const {
  // @@protoc_insertion_point(field_get:OnvifCli.OnvifCliCmd.loginResp)
  return has_loginresp()
      ? *cmd_.loginresp_
      : ::OnvifCliDeviceLoginResp::default_instance();
}
::OnvifCliDeviceLoginResp* OnvifCliCmd::mutable_loginresp() {
  if (!has_loginresp()) {
    clear_cmd();
    set_has_loginresp();
    cmd_.loginresp_ = new ::OnvifCliDeviceLoginResp;
  }
  // @@protoc_insertion_point(field_mutable:OnvifCli.OnvifCliCmd.loginResp)
  return cmd_.loginresp_;
}
::OnvifCliDeviceLoginResp* OnvifCliCmd::release_loginresp() {
  // @@protoc_insertion_point(field_release:OnvifCli.OnvifCliCmd.loginResp)
  if (has_loginresp()) {
    clear_has_cmd();
    ::OnvifCliDeviceLoginResp* temp = cmd_.loginresp_;
    cmd_.loginresp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void OnvifCliCmd::set_allocated_loginresp(::OnvifCliDeviceLoginResp* loginresp) {
  clear_cmd();
  if (loginresp) {
    set_has_loginresp();
    cmd_.loginresp_ = loginresp;
  }
  // @@protoc_insertion_point(field_set_allocated:OnvifCli.OnvifCliCmd.loginResp)
}

bool OnvifCliCmd::has_cmd() const {
  return cmd_case() != CMD_NOT_SET;
}
void OnvifCliCmd::clear_has_cmd() {
  _oneof_case_[0] = CMD_NOT_SET;
}
OnvifCliCmd::CmdCase OnvifCliCmd::cmd_case() const {
  return OnvifCliCmd::CmdCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace OnvifCli

// @@protoc_insertion_point(global_scope)
