/* soapDeviceBindingProxy.h
   Generated by gSOAP 2.8.17r from onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapDeviceBindingProxy_H
#define soapDeviceBindingProxy_H
#include "soapH.h"

class SOAP_CMAC DeviceBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'DeviceBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	DeviceBindingProxy();
	/// Construct from another engine state
	DeviceBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	DeviceBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	DeviceBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	DeviceBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	DeviceBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~DeviceBindingProxy();
	/// Initializer used by constructors
	virtual	void DeviceBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(struct _wsse__Security *wsse__Security, char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'GetServices' (returns error code or SOAP_OK)
	virtual	int GetServices(_tds__GetServices *tds__GetServices, _tds__GetServicesResponse *tds__GetServicesResponse) { return this->GetServices(NULL, NULL, tds__GetServices, tds__GetServicesResponse); }
	virtual	int GetServices(const char *endpoint, const char *soap_action, _tds__GetServices *tds__GetServices, _tds__GetServicesResponse *tds__GetServicesResponse);

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities(_tds__GetServiceCapabilities *tds__GetServiceCapabilities, _tds__GetServiceCapabilitiesResponse *tds__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, tds__GetServiceCapabilities, tds__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities(const char *endpoint, const char *soap_action, _tds__GetServiceCapabilities *tds__GetServiceCapabilities, _tds__GetServiceCapabilitiesResponse *tds__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetDeviceInformation' (returns error code or SOAP_OK)
	virtual	int GetDeviceInformation(_tds__GetDeviceInformation *tds__GetDeviceInformation, _tds__GetDeviceInformationResponse *tds__GetDeviceInformationResponse) { return this->GetDeviceInformation(NULL, NULL, tds__GetDeviceInformation, tds__GetDeviceInformationResponse); }
	virtual	int GetDeviceInformation(const char *endpoint, const char *soap_action, _tds__GetDeviceInformation *tds__GetDeviceInformation, _tds__GetDeviceInformationResponse *tds__GetDeviceInformationResponse);

	/// Web service operation 'SetSystemDateAndTime' (returns error code or SOAP_OK)
	virtual	int SetSystemDateAndTime(_tds__SetSystemDateAndTime *tds__SetSystemDateAndTime, _tds__SetSystemDateAndTimeResponse *tds__SetSystemDateAndTimeResponse) { return this->SetSystemDateAndTime(NULL, NULL, tds__SetSystemDateAndTime, tds__SetSystemDateAndTimeResponse); }
	virtual	int SetSystemDateAndTime(const char *endpoint, const char *soap_action, _tds__SetSystemDateAndTime *tds__SetSystemDateAndTime, _tds__SetSystemDateAndTimeResponse *tds__SetSystemDateAndTimeResponse);

	/// Web service operation 'GetSystemDateAndTime' (returns error code or SOAP_OK)
	virtual	int GetSystemDateAndTime(_tds__GetSystemDateAndTime *tds__GetSystemDateAndTime, _tds__GetSystemDateAndTimeResponse *tds__GetSystemDateAndTimeResponse) { return this->GetSystemDateAndTime(NULL, NULL, tds__GetSystemDateAndTime, tds__GetSystemDateAndTimeResponse); }
	virtual	int GetSystemDateAndTime(const char *endpoint, const char *soap_action, _tds__GetSystemDateAndTime *tds__GetSystemDateAndTime, _tds__GetSystemDateAndTimeResponse *tds__GetSystemDateAndTimeResponse);

	/// Web service operation 'SetSystemFactoryDefault' (returns error code or SOAP_OK)
	virtual	int SetSystemFactoryDefault(_tds__SetSystemFactoryDefault *tds__SetSystemFactoryDefault, _tds__SetSystemFactoryDefaultResponse *tds__SetSystemFactoryDefaultResponse) { return this->SetSystemFactoryDefault(NULL, NULL, tds__SetSystemFactoryDefault, tds__SetSystemFactoryDefaultResponse); }
	virtual	int SetSystemFactoryDefault(const char *endpoint, const char *soap_action, _tds__SetSystemFactoryDefault *tds__SetSystemFactoryDefault, _tds__SetSystemFactoryDefaultResponse *tds__SetSystemFactoryDefaultResponse);

	/// Web service operation 'UpgradeSystemFirmware' (returns error code or SOAP_OK)
	virtual	int UpgradeSystemFirmware(_tds__UpgradeSystemFirmware *tds__UpgradeSystemFirmware, _tds__UpgradeSystemFirmwareResponse *tds__UpgradeSystemFirmwareResponse) { return this->UpgradeSystemFirmware(NULL, NULL, tds__UpgradeSystemFirmware, tds__UpgradeSystemFirmwareResponse); }
	virtual	int UpgradeSystemFirmware(const char *endpoint, const char *soap_action, _tds__UpgradeSystemFirmware *tds__UpgradeSystemFirmware, _tds__UpgradeSystemFirmwareResponse *tds__UpgradeSystemFirmwareResponse);

	/// Web service operation 'SystemReboot' (returns error code or SOAP_OK)
	virtual	int SystemReboot(_tds__SystemReboot *tds__SystemReboot, _tds__SystemRebootResponse *tds__SystemRebootResponse) { return this->SystemReboot(NULL, NULL, tds__SystemReboot, tds__SystemRebootResponse); }
	virtual	int SystemReboot(const char *endpoint, const char *soap_action, _tds__SystemReboot *tds__SystemReboot, _tds__SystemRebootResponse *tds__SystemRebootResponse);

	/// Web service operation 'RestoreSystem' (returns error code or SOAP_OK)
	virtual	int RestoreSystem(_tds__RestoreSystem *tds__RestoreSystem, _tds__RestoreSystemResponse *tds__RestoreSystemResponse) { return this->RestoreSystem(NULL, NULL, tds__RestoreSystem, tds__RestoreSystemResponse); }
	virtual	int RestoreSystem(const char *endpoint, const char *soap_action, _tds__RestoreSystem *tds__RestoreSystem, _tds__RestoreSystemResponse *tds__RestoreSystemResponse);

	/// Web service operation 'GetSystemBackup' (returns error code or SOAP_OK)
	virtual	int GetSystemBackup(_tds__GetSystemBackup *tds__GetSystemBackup, _tds__GetSystemBackupResponse *tds__GetSystemBackupResponse) { return this->GetSystemBackup(NULL, NULL, tds__GetSystemBackup, tds__GetSystemBackupResponse); }
	virtual	int GetSystemBackup(const char *endpoint, const char *soap_action, _tds__GetSystemBackup *tds__GetSystemBackup, _tds__GetSystemBackupResponse *tds__GetSystemBackupResponse);

	/// Web service operation 'GetSystemLog' (returns error code or SOAP_OK)
	virtual	int GetSystemLog(_tds__GetSystemLog *tds__GetSystemLog, _tds__GetSystemLogResponse *tds__GetSystemLogResponse) { return this->GetSystemLog(NULL, NULL, tds__GetSystemLog, tds__GetSystemLogResponse); }
	virtual	int GetSystemLog(const char *endpoint, const char *soap_action, _tds__GetSystemLog *tds__GetSystemLog, _tds__GetSystemLogResponse *tds__GetSystemLogResponse);

	/// Web service operation 'GetSystemSupportInformation' (returns error code or SOAP_OK)
	virtual	int GetSystemSupportInformation(_tds__GetSystemSupportInformation *tds__GetSystemSupportInformation, _tds__GetSystemSupportInformationResponse *tds__GetSystemSupportInformationResponse) { return this->GetSystemSupportInformation(NULL, NULL, tds__GetSystemSupportInformation, tds__GetSystemSupportInformationResponse); }
	virtual	int GetSystemSupportInformation(const char *endpoint, const char *soap_action, _tds__GetSystemSupportInformation *tds__GetSystemSupportInformation, _tds__GetSystemSupportInformationResponse *tds__GetSystemSupportInformationResponse);

	/// Web service operation 'GetScopes' (returns error code or SOAP_OK)
	virtual	int GetScopes(_tds__GetScopes *tds__GetScopes, _tds__GetScopesResponse *tds__GetScopesResponse) { return this->GetScopes(NULL, NULL, tds__GetScopes, tds__GetScopesResponse); }
	virtual	int GetScopes(const char *endpoint, const char *soap_action, _tds__GetScopes *tds__GetScopes, _tds__GetScopesResponse *tds__GetScopesResponse);

	/// Web service operation 'SetScopes' (returns error code or SOAP_OK)
	virtual	int SetScopes(_tds__SetScopes *tds__SetScopes, _tds__SetScopesResponse *tds__SetScopesResponse) { return this->SetScopes(NULL, NULL, tds__SetScopes, tds__SetScopesResponse); }
	virtual	int SetScopes(const char *endpoint, const char *soap_action, _tds__SetScopes *tds__SetScopes, _tds__SetScopesResponse *tds__SetScopesResponse);

	/// Web service operation 'AddScopes' (returns error code or SOAP_OK)
	virtual	int AddScopes(_tds__AddScopes *tds__AddScopes, _tds__AddScopesResponse *tds__AddScopesResponse) { return this->AddScopes(NULL, NULL, tds__AddScopes, tds__AddScopesResponse); }
	virtual	int AddScopes(const char *endpoint, const char *soap_action, _tds__AddScopes *tds__AddScopes, _tds__AddScopesResponse *tds__AddScopesResponse);

	/// Web service operation 'RemoveScopes' (returns error code or SOAP_OK)
	virtual	int RemoveScopes(_tds__RemoveScopes *tds__RemoveScopes, _tds__RemoveScopesResponse *tds__RemoveScopesResponse) { return this->RemoveScopes(NULL, NULL, tds__RemoveScopes, tds__RemoveScopesResponse); }
	virtual	int RemoveScopes(const char *endpoint, const char *soap_action, _tds__RemoveScopes *tds__RemoveScopes, _tds__RemoveScopesResponse *tds__RemoveScopesResponse);

	/// Web service operation 'GetDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int GetDiscoveryMode(_tds__GetDiscoveryMode *tds__GetDiscoveryMode, _tds__GetDiscoveryModeResponse *tds__GetDiscoveryModeResponse) { return this->GetDiscoveryMode(NULL, NULL, tds__GetDiscoveryMode, tds__GetDiscoveryModeResponse); }
	virtual	int GetDiscoveryMode(const char *endpoint, const char *soap_action, _tds__GetDiscoveryMode *tds__GetDiscoveryMode, _tds__GetDiscoveryModeResponse *tds__GetDiscoveryModeResponse);

	/// Web service operation 'SetDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int SetDiscoveryMode(_tds__SetDiscoveryMode *tds__SetDiscoveryMode, _tds__SetDiscoveryModeResponse *tds__SetDiscoveryModeResponse) { return this->SetDiscoveryMode(NULL, NULL, tds__SetDiscoveryMode, tds__SetDiscoveryModeResponse); }
	virtual	int SetDiscoveryMode(const char *endpoint, const char *soap_action, _tds__SetDiscoveryMode *tds__SetDiscoveryMode, _tds__SetDiscoveryModeResponse *tds__SetDiscoveryModeResponse);

	/// Web service operation 'GetRemoteDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int GetRemoteDiscoveryMode(_tds__GetRemoteDiscoveryMode *tds__GetRemoteDiscoveryMode, _tds__GetRemoteDiscoveryModeResponse *tds__GetRemoteDiscoveryModeResponse) { return this->GetRemoteDiscoveryMode(NULL, NULL, tds__GetRemoteDiscoveryMode, tds__GetRemoteDiscoveryModeResponse); }
	virtual	int GetRemoteDiscoveryMode(const char *endpoint, const char *soap_action, _tds__GetRemoteDiscoveryMode *tds__GetRemoteDiscoveryMode, _tds__GetRemoteDiscoveryModeResponse *tds__GetRemoteDiscoveryModeResponse);

	/// Web service operation 'SetRemoteDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int SetRemoteDiscoveryMode(_tds__SetRemoteDiscoveryMode *tds__SetRemoteDiscoveryMode, _tds__SetRemoteDiscoveryModeResponse *tds__SetRemoteDiscoveryModeResponse) { return this->SetRemoteDiscoveryMode(NULL, NULL, tds__SetRemoteDiscoveryMode, tds__SetRemoteDiscoveryModeResponse); }
	virtual	int SetRemoteDiscoveryMode(const char *endpoint, const char *soap_action, _tds__SetRemoteDiscoveryMode *tds__SetRemoteDiscoveryMode, _tds__SetRemoteDiscoveryModeResponse *tds__SetRemoteDiscoveryModeResponse);

	/// Web service operation 'GetDPAddresses' (returns error code or SOAP_OK)
	virtual	int GetDPAddresses(_tds__GetDPAddresses *tds__GetDPAddresses, _tds__GetDPAddressesResponse *tds__GetDPAddressesResponse) { return this->GetDPAddresses(NULL, NULL, tds__GetDPAddresses, tds__GetDPAddressesResponse); }
	virtual	int GetDPAddresses(const char *endpoint, const char *soap_action, _tds__GetDPAddresses *tds__GetDPAddresses, _tds__GetDPAddressesResponse *tds__GetDPAddressesResponse);

	/// Web service operation 'GetEndpointReference' (returns error code or SOAP_OK)
	virtual	int GetEndpointReference(_tds__GetEndpointReference *tds__GetEndpointReference, _tds__GetEndpointReferenceResponse *tds__GetEndpointReferenceResponse) { return this->GetEndpointReference(NULL, NULL, tds__GetEndpointReference, tds__GetEndpointReferenceResponse); }
	virtual	int GetEndpointReference(const char *endpoint, const char *soap_action, _tds__GetEndpointReference *tds__GetEndpointReference, _tds__GetEndpointReferenceResponse *tds__GetEndpointReferenceResponse);

	/// Web service operation 'GetRemoteUser' (returns error code or SOAP_OK)
	virtual	int GetRemoteUser(_tds__GetRemoteUser *tds__GetRemoteUser, _tds__GetRemoteUserResponse *tds__GetRemoteUserResponse) { return this->GetRemoteUser(NULL, NULL, tds__GetRemoteUser, tds__GetRemoteUserResponse); }
	virtual	int GetRemoteUser(const char *endpoint, const char *soap_action, _tds__GetRemoteUser *tds__GetRemoteUser, _tds__GetRemoteUserResponse *tds__GetRemoteUserResponse);

	/// Web service operation 'SetRemoteUser' (returns error code or SOAP_OK)
	virtual	int SetRemoteUser(_tds__SetRemoteUser *tds__SetRemoteUser, _tds__SetRemoteUserResponse *tds__SetRemoteUserResponse) { return this->SetRemoteUser(NULL, NULL, tds__SetRemoteUser, tds__SetRemoteUserResponse); }
	virtual	int SetRemoteUser(const char *endpoint, const char *soap_action, _tds__SetRemoteUser *tds__SetRemoteUser, _tds__SetRemoteUserResponse *tds__SetRemoteUserResponse);

	/// Web service operation 'GetUsers' (returns error code or SOAP_OK)
	virtual	int GetUsers(_tds__GetUsers *tds__GetUsers, _tds__GetUsersResponse *tds__GetUsersResponse) { return this->GetUsers(NULL, NULL, tds__GetUsers, tds__GetUsersResponse); }
	virtual	int GetUsers(const char *endpoint, const char *soap_action, _tds__GetUsers *tds__GetUsers, _tds__GetUsersResponse *tds__GetUsersResponse);

	/// Web service operation 'CreateUsers' (returns error code or SOAP_OK)
	virtual	int CreateUsers(_tds__CreateUsers *tds__CreateUsers, _tds__CreateUsersResponse *tds__CreateUsersResponse) { return this->CreateUsers(NULL, NULL, tds__CreateUsers, tds__CreateUsersResponse); }
	virtual	int CreateUsers(const char *endpoint, const char *soap_action, _tds__CreateUsers *tds__CreateUsers, _tds__CreateUsersResponse *tds__CreateUsersResponse);

	/// Web service operation 'DeleteUsers' (returns error code or SOAP_OK)
	virtual	int DeleteUsers(_tds__DeleteUsers *tds__DeleteUsers, _tds__DeleteUsersResponse *tds__DeleteUsersResponse) { return this->DeleteUsers(NULL, NULL, tds__DeleteUsers, tds__DeleteUsersResponse); }
	virtual	int DeleteUsers(const char *endpoint, const char *soap_action, _tds__DeleteUsers *tds__DeleteUsers, _tds__DeleteUsersResponse *tds__DeleteUsersResponse);

	/// Web service operation 'SetUser' (returns error code or SOAP_OK)
	virtual	int SetUser(_tds__SetUser *tds__SetUser, _tds__SetUserResponse *tds__SetUserResponse) { return this->SetUser(NULL, NULL, tds__SetUser, tds__SetUserResponse); }
	virtual	int SetUser(const char *endpoint, const char *soap_action, _tds__SetUser *tds__SetUser, _tds__SetUserResponse *tds__SetUserResponse);

	/// Web service operation 'GetWsdlUrl' (returns error code or SOAP_OK)
	virtual	int GetWsdlUrl(_tds__GetWsdlUrl *tds__GetWsdlUrl, _tds__GetWsdlUrlResponse *tds__GetWsdlUrlResponse) { return this->GetWsdlUrl(NULL, NULL, tds__GetWsdlUrl, tds__GetWsdlUrlResponse); }
	virtual	int GetWsdlUrl(const char *endpoint, const char *soap_action, _tds__GetWsdlUrl *tds__GetWsdlUrl, _tds__GetWsdlUrlResponse *tds__GetWsdlUrlResponse);

	/// Web service operation 'GetCapabilities' (returns error code or SOAP_OK)
	virtual	int GetCapabilities(_tds__GetCapabilities *tds__GetCapabilities, _tds__GetCapabilitiesResponse *tds__GetCapabilitiesResponse) { return this->GetCapabilities(NULL, NULL, tds__GetCapabilities, tds__GetCapabilitiesResponse); }
	virtual	int GetCapabilities(const char *endpoint, const char *soap_action, _tds__GetCapabilities *tds__GetCapabilities, _tds__GetCapabilitiesResponse *tds__GetCapabilitiesResponse);

	/// Web service operation 'SetDPAddresses' (returns error code or SOAP_OK)
	virtual	int SetDPAddresses(_tds__SetDPAddresses *tds__SetDPAddresses, _tds__SetDPAddressesResponse *tds__SetDPAddressesResponse) { return this->SetDPAddresses(NULL, NULL, tds__SetDPAddresses, tds__SetDPAddressesResponse); }
	virtual	int SetDPAddresses(const char *endpoint, const char *soap_action, _tds__SetDPAddresses *tds__SetDPAddresses, _tds__SetDPAddressesResponse *tds__SetDPAddressesResponse);

	/// Web service operation 'GetHostname' (returns error code or SOAP_OK)
	virtual	int GetHostname(_tds__GetHostname *tds__GetHostname, _tds__GetHostnameResponse *tds__GetHostnameResponse) { return this->GetHostname(NULL, NULL, tds__GetHostname, tds__GetHostnameResponse); }
	virtual	int GetHostname(const char *endpoint, const char *soap_action, _tds__GetHostname *tds__GetHostname, _tds__GetHostnameResponse *tds__GetHostnameResponse);

	/// Web service operation 'SetHostname' (returns error code or SOAP_OK)
	virtual	int SetHostname(_tds__SetHostname *tds__SetHostname, _tds__SetHostnameResponse *tds__SetHostnameResponse) { return this->SetHostname(NULL, NULL, tds__SetHostname, tds__SetHostnameResponse); }
	virtual	int SetHostname(const char *endpoint, const char *soap_action, _tds__SetHostname *tds__SetHostname, _tds__SetHostnameResponse *tds__SetHostnameResponse);

	/// Web service operation 'SetHostnameFromDHCP' (returns error code or SOAP_OK)
	virtual	int SetHostnameFromDHCP(_tds__SetHostnameFromDHCP *tds__SetHostnameFromDHCP, _tds__SetHostnameFromDHCPResponse *tds__SetHostnameFromDHCPResponse) { return this->SetHostnameFromDHCP(NULL, NULL, tds__SetHostnameFromDHCP, tds__SetHostnameFromDHCPResponse); }
	virtual	int SetHostnameFromDHCP(const char *endpoint, const char *soap_action, _tds__SetHostnameFromDHCP *tds__SetHostnameFromDHCP, _tds__SetHostnameFromDHCPResponse *tds__SetHostnameFromDHCPResponse);

	/// Web service operation 'GetDNS' (returns error code or SOAP_OK)
	virtual	int GetDNS(_tds__GetDNS *tds__GetDNS, _tds__GetDNSResponse *tds__GetDNSResponse) { return this->GetDNS(NULL, NULL, tds__GetDNS, tds__GetDNSResponse); }
	virtual	int GetDNS(const char *endpoint, const char *soap_action, _tds__GetDNS *tds__GetDNS, _tds__GetDNSResponse *tds__GetDNSResponse);

	/// Web service operation 'SetDNS' (returns error code or SOAP_OK)
	virtual	int SetDNS(_tds__SetDNS *tds__SetDNS, _tds__SetDNSResponse *tds__SetDNSResponse) { return this->SetDNS(NULL, NULL, tds__SetDNS, tds__SetDNSResponse); }
	virtual	int SetDNS(const char *endpoint, const char *soap_action, _tds__SetDNS *tds__SetDNS, _tds__SetDNSResponse *tds__SetDNSResponse);

	/// Web service operation 'GetNTP' (returns error code or SOAP_OK)
	virtual	int GetNTP(_tds__GetNTP *tds__GetNTP, _tds__GetNTPResponse *tds__GetNTPResponse) { return this->GetNTP(NULL, NULL, tds__GetNTP, tds__GetNTPResponse); }
	virtual	int GetNTP(const char *endpoint, const char *soap_action, _tds__GetNTP *tds__GetNTP, _tds__GetNTPResponse *tds__GetNTPResponse);

	/// Web service operation 'SetNTP' (returns error code or SOAP_OK)
	virtual	int SetNTP(_tds__SetNTP *tds__SetNTP, _tds__SetNTPResponse *tds__SetNTPResponse) { return this->SetNTP(NULL, NULL, tds__SetNTP, tds__SetNTPResponse); }
	virtual	int SetNTP(const char *endpoint, const char *soap_action, _tds__SetNTP *tds__SetNTP, _tds__SetNTPResponse *tds__SetNTPResponse);

	/// Web service operation 'GetDynamicDNS' (returns error code or SOAP_OK)
	virtual	int GetDynamicDNS(_tds__GetDynamicDNS *tds__GetDynamicDNS, _tds__GetDynamicDNSResponse *tds__GetDynamicDNSResponse) { return this->GetDynamicDNS(NULL, NULL, tds__GetDynamicDNS, tds__GetDynamicDNSResponse); }
	virtual	int GetDynamicDNS(const char *endpoint, const char *soap_action, _tds__GetDynamicDNS *tds__GetDynamicDNS, _tds__GetDynamicDNSResponse *tds__GetDynamicDNSResponse);

	/// Web service operation 'SetDynamicDNS' (returns error code or SOAP_OK)
	virtual	int SetDynamicDNS(_tds__SetDynamicDNS *tds__SetDynamicDNS, _tds__SetDynamicDNSResponse *tds__SetDynamicDNSResponse) { return this->SetDynamicDNS(NULL, NULL, tds__SetDynamicDNS, tds__SetDynamicDNSResponse); }
	virtual	int SetDynamicDNS(const char *endpoint, const char *soap_action, _tds__SetDynamicDNS *tds__SetDynamicDNS, _tds__SetDynamicDNSResponse *tds__SetDynamicDNSResponse);

	/// Web service operation 'GetNetworkInterfaces' (returns error code or SOAP_OK)
	virtual	int GetNetworkInterfaces(_tds__GetNetworkInterfaces *tds__GetNetworkInterfaces, _tds__GetNetworkInterfacesResponse *tds__GetNetworkInterfacesResponse) { return this->GetNetworkInterfaces(NULL, NULL, tds__GetNetworkInterfaces, tds__GetNetworkInterfacesResponse); }
	virtual	int GetNetworkInterfaces(const char *endpoint, const char *soap_action, _tds__GetNetworkInterfaces *tds__GetNetworkInterfaces, _tds__GetNetworkInterfacesResponse *tds__GetNetworkInterfacesResponse);

	/// Web service operation 'SetNetworkInterfaces' (returns error code or SOAP_OK)
	virtual	int SetNetworkInterfaces(_tds__SetNetworkInterfaces *tds__SetNetworkInterfaces, _tds__SetNetworkInterfacesResponse *tds__SetNetworkInterfacesResponse) { return this->SetNetworkInterfaces(NULL, NULL, tds__SetNetworkInterfaces, tds__SetNetworkInterfacesResponse); }
	virtual	int SetNetworkInterfaces(const char *endpoint, const char *soap_action, _tds__SetNetworkInterfaces *tds__SetNetworkInterfaces, _tds__SetNetworkInterfacesResponse *tds__SetNetworkInterfacesResponse);

	/// Web service operation 'GetNetworkProtocols' (returns error code or SOAP_OK)
	virtual	int GetNetworkProtocols(_tds__GetNetworkProtocols *tds__GetNetworkProtocols, _tds__GetNetworkProtocolsResponse *tds__GetNetworkProtocolsResponse) { return this->GetNetworkProtocols(NULL, NULL, tds__GetNetworkProtocols, tds__GetNetworkProtocolsResponse); }
	virtual	int GetNetworkProtocols(const char *endpoint, const char *soap_action, _tds__GetNetworkProtocols *tds__GetNetworkProtocols, _tds__GetNetworkProtocolsResponse *tds__GetNetworkProtocolsResponse);

	/// Web service operation 'SetNetworkProtocols' (returns error code or SOAP_OK)
	virtual	int SetNetworkProtocols(_tds__SetNetworkProtocols *tds__SetNetworkProtocols, _tds__SetNetworkProtocolsResponse *tds__SetNetworkProtocolsResponse) { return this->SetNetworkProtocols(NULL, NULL, tds__SetNetworkProtocols, tds__SetNetworkProtocolsResponse); }
	virtual	int SetNetworkProtocols(const char *endpoint, const char *soap_action, _tds__SetNetworkProtocols *tds__SetNetworkProtocols, _tds__SetNetworkProtocolsResponse *tds__SetNetworkProtocolsResponse);

	/// Web service operation 'GetNetworkDefaultGateway' (returns error code or SOAP_OK)
	virtual	int GetNetworkDefaultGateway(_tds__GetNetworkDefaultGateway *tds__GetNetworkDefaultGateway, _tds__GetNetworkDefaultGatewayResponse *tds__GetNetworkDefaultGatewayResponse) { return this->GetNetworkDefaultGateway(NULL, NULL, tds__GetNetworkDefaultGateway, tds__GetNetworkDefaultGatewayResponse); }
	virtual	int GetNetworkDefaultGateway(const char *endpoint, const char *soap_action, _tds__GetNetworkDefaultGateway *tds__GetNetworkDefaultGateway, _tds__GetNetworkDefaultGatewayResponse *tds__GetNetworkDefaultGatewayResponse);

	/// Web service operation 'SetNetworkDefaultGateway' (returns error code or SOAP_OK)
	virtual	int SetNetworkDefaultGateway(_tds__SetNetworkDefaultGateway *tds__SetNetworkDefaultGateway, _tds__SetNetworkDefaultGatewayResponse *tds__SetNetworkDefaultGatewayResponse) { return this->SetNetworkDefaultGateway(NULL, NULL, tds__SetNetworkDefaultGateway, tds__SetNetworkDefaultGatewayResponse); }
	virtual	int SetNetworkDefaultGateway(const char *endpoint, const char *soap_action, _tds__SetNetworkDefaultGateway *tds__SetNetworkDefaultGateway, _tds__SetNetworkDefaultGatewayResponse *tds__SetNetworkDefaultGatewayResponse);

	/// Web service operation 'GetZeroConfiguration' (returns error code or SOAP_OK)
	virtual	int GetZeroConfiguration(_tds__GetZeroConfiguration *tds__GetZeroConfiguration, _tds__GetZeroConfigurationResponse *tds__GetZeroConfigurationResponse) { return this->GetZeroConfiguration(NULL, NULL, tds__GetZeroConfiguration, tds__GetZeroConfigurationResponse); }
	virtual	int GetZeroConfiguration(const char *endpoint, const char *soap_action, _tds__GetZeroConfiguration *tds__GetZeroConfiguration, _tds__GetZeroConfigurationResponse *tds__GetZeroConfigurationResponse);

	/// Web service operation 'SetZeroConfiguration' (returns error code or SOAP_OK)
	virtual	int SetZeroConfiguration(_tds__SetZeroConfiguration *tds__SetZeroConfiguration, _tds__SetZeroConfigurationResponse *tds__SetZeroConfigurationResponse) { return this->SetZeroConfiguration(NULL, NULL, tds__SetZeroConfiguration, tds__SetZeroConfigurationResponse); }
	virtual	int SetZeroConfiguration(const char *endpoint, const char *soap_action, _tds__SetZeroConfiguration *tds__SetZeroConfiguration, _tds__SetZeroConfigurationResponse *tds__SetZeroConfigurationResponse);

	/// Web service operation 'GetIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int GetIPAddressFilter(_tds__GetIPAddressFilter *tds__GetIPAddressFilter, _tds__GetIPAddressFilterResponse *tds__GetIPAddressFilterResponse) { return this->GetIPAddressFilter(NULL, NULL, tds__GetIPAddressFilter, tds__GetIPAddressFilterResponse); }
	virtual	int GetIPAddressFilter(const char *endpoint, const char *soap_action, _tds__GetIPAddressFilter *tds__GetIPAddressFilter, _tds__GetIPAddressFilterResponse *tds__GetIPAddressFilterResponse);

	/// Web service operation 'SetIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int SetIPAddressFilter(_tds__SetIPAddressFilter *tds__SetIPAddressFilter, _tds__SetIPAddressFilterResponse *tds__SetIPAddressFilterResponse) { return this->SetIPAddressFilter(NULL, NULL, tds__SetIPAddressFilter, tds__SetIPAddressFilterResponse); }
	virtual	int SetIPAddressFilter(const char *endpoint, const char *soap_action, _tds__SetIPAddressFilter *tds__SetIPAddressFilter, _tds__SetIPAddressFilterResponse *tds__SetIPAddressFilterResponse);

	/// Web service operation 'AddIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int AddIPAddressFilter(_tds__AddIPAddressFilter *tds__AddIPAddressFilter, _tds__AddIPAddressFilterResponse *tds__AddIPAddressFilterResponse) { return this->AddIPAddressFilter(NULL, NULL, tds__AddIPAddressFilter, tds__AddIPAddressFilterResponse); }
	virtual	int AddIPAddressFilter(const char *endpoint, const char *soap_action, _tds__AddIPAddressFilter *tds__AddIPAddressFilter, _tds__AddIPAddressFilterResponse *tds__AddIPAddressFilterResponse);

	/// Web service operation 'RemoveIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int RemoveIPAddressFilter(_tds__RemoveIPAddressFilter *tds__RemoveIPAddressFilter, _tds__RemoveIPAddressFilterResponse *tds__RemoveIPAddressFilterResponse) { return this->RemoveIPAddressFilter(NULL, NULL, tds__RemoveIPAddressFilter, tds__RemoveIPAddressFilterResponse); }
	virtual	int RemoveIPAddressFilter(const char *endpoint, const char *soap_action, _tds__RemoveIPAddressFilter *tds__RemoveIPAddressFilter, _tds__RemoveIPAddressFilterResponse *tds__RemoveIPAddressFilterResponse);

	/// Web service operation 'GetAccessPolicy' (returns error code or SOAP_OK)
	virtual	int GetAccessPolicy(_tds__GetAccessPolicy *tds__GetAccessPolicy, _tds__GetAccessPolicyResponse *tds__GetAccessPolicyResponse) { return this->GetAccessPolicy(NULL, NULL, tds__GetAccessPolicy, tds__GetAccessPolicyResponse); }
	virtual	int GetAccessPolicy(const char *endpoint, const char *soap_action, _tds__GetAccessPolicy *tds__GetAccessPolicy, _tds__GetAccessPolicyResponse *tds__GetAccessPolicyResponse);

	/// Web service operation 'SetAccessPolicy' (returns error code or SOAP_OK)
	virtual	int SetAccessPolicy(_tds__SetAccessPolicy *tds__SetAccessPolicy, _tds__SetAccessPolicyResponse *tds__SetAccessPolicyResponse) { return this->SetAccessPolicy(NULL, NULL, tds__SetAccessPolicy, tds__SetAccessPolicyResponse); }
	virtual	int SetAccessPolicy(const char *endpoint, const char *soap_action, _tds__SetAccessPolicy *tds__SetAccessPolicy, _tds__SetAccessPolicyResponse *tds__SetAccessPolicyResponse);

	/// Web service operation 'CreateCertificate' (returns error code or SOAP_OK)
	virtual	int CreateCertificate(_tds__CreateCertificate *tds__CreateCertificate, _tds__CreateCertificateResponse *tds__CreateCertificateResponse) { return this->CreateCertificate(NULL, NULL, tds__CreateCertificate, tds__CreateCertificateResponse); }
	virtual	int CreateCertificate(const char *endpoint, const char *soap_action, _tds__CreateCertificate *tds__CreateCertificate, _tds__CreateCertificateResponse *tds__CreateCertificateResponse);

	/// Web service operation 'GetCertificates' (returns error code or SOAP_OK)
	virtual	int GetCertificates(_tds__GetCertificates *tds__GetCertificates, _tds__GetCertificatesResponse *tds__GetCertificatesResponse) { return this->GetCertificates(NULL, NULL, tds__GetCertificates, tds__GetCertificatesResponse); }
	virtual	int GetCertificates(const char *endpoint, const char *soap_action, _tds__GetCertificates *tds__GetCertificates, _tds__GetCertificatesResponse *tds__GetCertificatesResponse);

	/// Web service operation 'GetCertificatesStatus' (returns error code or SOAP_OK)
	virtual	int GetCertificatesStatus(_tds__GetCertificatesStatus *tds__GetCertificatesStatus, _tds__GetCertificatesStatusResponse *tds__GetCertificatesStatusResponse) { return this->GetCertificatesStatus(NULL, NULL, tds__GetCertificatesStatus, tds__GetCertificatesStatusResponse); }
	virtual	int GetCertificatesStatus(const char *endpoint, const char *soap_action, _tds__GetCertificatesStatus *tds__GetCertificatesStatus, _tds__GetCertificatesStatusResponse *tds__GetCertificatesStatusResponse);

	/// Web service operation 'SetCertificatesStatus' (returns error code or SOAP_OK)
	virtual	int SetCertificatesStatus(_tds__SetCertificatesStatus *tds__SetCertificatesStatus, _tds__SetCertificatesStatusResponse *tds__SetCertificatesStatusResponse) { return this->SetCertificatesStatus(NULL, NULL, tds__SetCertificatesStatus, tds__SetCertificatesStatusResponse); }
	virtual	int SetCertificatesStatus(const char *endpoint, const char *soap_action, _tds__SetCertificatesStatus *tds__SetCertificatesStatus, _tds__SetCertificatesStatusResponse *tds__SetCertificatesStatusResponse);

	/// Web service operation 'DeleteCertificates' (returns error code or SOAP_OK)
	virtual	int DeleteCertificates(_tds__DeleteCertificates *tds__DeleteCertificates, _tds__DeleteCertificatesResponse *tds__DeleteCertificatesResponse) { return this->DeleteCertificates(NULL, NULL, tds__DeleteCertificates, tds__DeleteCertificatesResponse); }
	virtual	int DeleteCertificates(const char *endpoint, const char *soap_action, _tds__DeleteCertificates *tds__DeleteCertificates, _tds__DeleteCertificatesResponse *tds__DeleteCertificatesResponse);

	/// Web service operation 'GetPkcs10Request' (returns error code or SOAP_OK)
	virtual	int GetPkcs10Request(_tds__GetPkcs10Request *tds__GetPkcs10Request, _tds__GetPkcs10RequestResponse *tds__GetPkcs10RequestResponse) { return this->GetPkcs10Request(NULL, NULL, tds__GetPkcs10Request, tds__GetPkcs10RequestResponse); }
	virtual	int GetPkcs10Request(const char *endpoint, const char *soap_action, _tds__GetPkcs10Request *tds__GetPkcs10Request, _tds__GetPkcs10RequestResponse *tds__GetPkcs10RequestResponse);

	/// Web service operation 'LoadCertificates' (returns error code or SOAP_OK)
	virtual	int LoadCertificates(_tds__LoadCertificates *tds__LoadCertificates, _tds__LoadCertificatesResponse *tds__LoadCertificatesResponse) { return this->LoadCertificates(NULL, NULL, tds__LoadCertificates, tds__LoadCertificatesResponse); }
	virtual	int LoadCertificates(const char *endpoint, const char *soap_action, _tds__LoadCertificates *tds__LoadCertificates, _tds__LoadCertificatesResponse *tds__LoadCertificatesResponse);

	/// Web service operation 'GetClientCertificateMode' (returns error code or SOAP_OK)
	virtual	int GetClientCertificateMode(_tds__GetClientCertificateMode *tds__GetClientCertificateMode, _tds__GetClientCertificateModeResponse *tds__GetClientCertificateModeResponse) { return this->GetClientCertificateMode(NULL, NULL, tds__GetClientCertificateMode, tds__GetClientCertificateModeResponse); }
	virtual	int GetClientCertificateMode(const char *endpoint, const char *soap_action, _tds__GetClientCertificateMode *tds__GetClientCertificateMode, _tds__GetClientCertificateModeResponse *tds__GetClientCertificateModeResponse);

	/// Web service operation 'SetClientCertificateMode' (returns error code or SOAP_OK)
	virtual	int SetClientCertificateMode(_tds__SetClientCertificateMode *tds__SetClientCertificateMode, _tds__SetClientCertificateModeResponse *tds__SetClientCertificateModeResponse) { return this->SetClientCertificateMode(NULL, NULL, tds__SetClientCertificateMode, tds__SetClientCertificateModeResponse); }
	virtual	int SetClientCertificateMode(const char *endpoint, const char *soap_action, _tds__SetClientCertificateMode *tds__SetClientCertificateMode, _tds__SetClientCertificateModeResponse *tds__SetClientCertificateModeResponse);

	/// Web service operation 'GetRelayOutputs' (returns error code or SOAP_OK)
	virtual	int GetRelayOutputs(_tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse *tds__GetRelayOutputsResponse) { return this->GetRelayOutputs(NULL, NULL, tds__GetRelayOutputs, tds__GetRelayOutputsResponse); }
	virtual	int GetRelayOutputs(const char *endpoint, const char *soap_action, _tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse *tds__GetRelayOutputsResponse);

	/// Web service operation 'SetRelayOutputSettings' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputSettings(_tds__SetRelayOutputSettings *tds__SetRelayOutputSettings, _tds__SetRelayOutputSettingsResponse *tds__SetRelayOutputSettingsResponse) { return this->SetRelayOutputSettings(NULL, NULL, tds__SetRelayOutputSettings, tds__SetRelayOutputSettingsResponse); }
	virtual	int SetRelayOutputSettings(const char *endpoint, const char *soap_action, _tds__SetRelayOutputSettings *tds__SetRelayOutputSettings, _tds__SetRelayOutputSettingsResponse *tds__SetRelayOutputSettingsResponse);

	/// Web service operation 'SetRelayOutputState' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputState(_tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse *tds__SetRelayOutputStateResponse) { return this->SetRelayOutputState(NULL, NULL, tds__SetRelayOutputState, tds__SetRelayOutputStateResponse); }
	virtual	int SetRelayOutputState(const char *endpoint, const char *soap_action, _tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse *tds__SetRelayOutputStateResponse);

	/// Web service operation 'SendAuxiliaryCommand' (returns error code or SOAP_OK)
	virtual	int SendAuxiliaryCommand(_tds__SendAuxiliaryCommand *tds__SendAuxiliaryCommand, _tds__SendAuxiliaryCommandResponse *tds__SendAuxiliaryCommandResponse) { return this->SendAuxiliaryCommand(NULL, NULL, tds__SendAuxiliaryCommand, tds__SendAuxiliaryCommandResponse); }
	virtual	int SendAuxiliaryCommand(const char *endpoint, const char *soap_action, _tds__SendAuxiliaryCommand *tds__SendAuxiliaryCommand, _tds__SendAuxiliaryCommandResponse *tds__SendAuxiliaryCommandResponse);

	/// Web service operation 'GetCACertificates' (returns error code or SOAP_OK)
	virtual	int GetCACertificates(_tds__GetCACertificates *tds__GetCACertificates, _tds__GetCACertificatesResponse *tds__GetCACertificatesResponse) { return this->GetCACertificates(NULL, NULL, tds__GetCACertificates, tds__GetCACertificatesResponse); }
	virtual	int GetCACertificates(const char *endpoint, const char *soap_action, _tds__GetCACertificates *tds__GetCACertificates, _tds__GetCACertificatesResponse *tds__GetCACertificatesResponse);

	/// Web service operation 'LoadCertificateWithPrivateKey' (returns error code or SOAP_OK)
	virtual	int LoadCertificateWithPrivateKey(_tds__LoadCertificateWithPrivateKey *tds__LoadCertificateWithPrivateKey, _tds__LoadCertificateWithPrivateKeyResponse *tds__LoadCertificateWithPrivateKeyResponse) { return this->LoadCertificateWithPrivateKey(NULL, NULL, tds__LoadCertificateWithPrivateKey, tds__LoadCertificateWithPrivateKeyResponse); }
	virtual	int LoadCertificateWithPrivateKey(const char *endpoint, const char *soap_action, _tds__LoadCertificateWithPrivateKey *tds__LoadCertificateWithPrivateKey, _tds__LoadCertificateWithPrivateKeyResponse *tds__LoadCertificateWithPrivateKeyResponse);

	/// Web service operation 'GetCertificateInformation' (returns error code or SOAP_OK)
	virtual	int GetCertificateInformation(_tds__GetCertificateInformation *tds__GetCertificateInformation, _tds__GetCertificateInformationResponse *tds__GetCertificateInformationResponse) { return this->GetCertificateInformation(NULL, NULL, tds__GetCertificateInformation, tds__GetCertificateInformationResponse); }
	virtual	int GetCertificateInformation(const char *endpoint, const char *soap_action, _tds__GetCertificateInformation *tds__GetCertificateInformation, _tds__GetCertificateInformationResponse *tds__GetCertificateInformationResponse);

	/// Web service operation 'LoadCACertificates' (returns error code or SOAP_OK)
	virtual	int LoadCACertificates(_tds__LoadCACertificates *tds__LoadCACertificates, _tds__LoadCACertificatesResponse *tds__LoadCACertificatesResponse) { return this->LoadCACertificates(NULL, NULL, tds__LoadCACertificates, tds__LoadCACertificatesResponse); }
	virtual	int LoadCACertificates(const char *endpoint, const char *soap_action, _tds__LoadCACertificates *tds__LoadCACertificates, _tds__LoadCACertificatesResponse *tds__LoadCACertificatesResponse);

	/// Web service operation 'CreateDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int CreateDot1XConfiguration(_tds__CreateDot1XConfiguration *tds__CreateDot1XConfiguration, _tds__CreateDot1XConfigurationResponse *tds__CreateDot1XConfigurationResponse) { return this->CreateDot1XConfiguration(NULL, NULL, tds__CreateDot1XConfiguration, tds__CreateDot1XConfigurationResponse); }
	virtual	int CreateDot1XConfiguration(const char *endpoint, const char *soap_action, _tds__CreateDot1XConfiguration *tds__CreateDot1XConfiguration, _tds__CreateDot1XConfigurationResponse *tds__CreateDot1XConfigurationResponse);

	/// Web service operation 'SetDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int SetDot1XConfiguration(_tds__SetDot1XConfiguration *tds__SetDot1XConfiguration, _tds__SetDot1XConfigurationResponse *tds__SetDot1XConfigurationResponse) { return this->SetDot1XConfiguration(NULL, NULL, tds__SetDot1XConfiguration, tds__SetDot1XConfigurationResponse); }
	virtual	int SetDot1XConfiguration(const char *endpoint, const char *soap_action, _tds__SetDot1XConfiguration *tds__SetDot1XConfiguration, _tds__SetDot1XConfigurationResponse *tds__SetDot1XConfigurationResponse);

	/// Web service operation 'GetDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int GetDot1XConfiguration(_tds__GetDot1XConfiguration *tds__GetDot1XConfiguration, _tds__GetDot1XConfigurationResponse *tds__GetDot1XConfigurationResponse) { return this->GetDot1XConfiguration(NULL, NULL, tds__GetDot1XConfiguration, tds__GetDot1XConfigurationResponse); }
	virtual	int GetDot1XConfiguration(const char *endpoint, const char *soap_action, _tds__GetDot1XConfiguration *tds__GetDot1XConfiguration, _tds__GetDot1XConfigurationResponse *tds__GetDot1XConfigurationResponse);

	/// Web service operation 'GetDot1XConfigurations' (returns error code or SOAP_OK)
	virtual	int GetDot1XConfigurations(_tds__GetDot1XConfigurations *tds__GetDot1XConfigurations, _tds__GetDot1XConfigurationsResponse *tds__GetDot1XConfigurationsResponse) { return this->GetDot1XConfigurations(NULL, NULL, tds__GetDot1XConfigurations, tds__GetDot1XConfigurationsResponse); }
	virtual	int GetDot1XConfigurations(const char *endpoint, const char *soap_action, _tds__GetDot1XConfigurations *tds__GetDot1XConfigurations, _tds__GetDot1XConfigurationsResponse *tds__GetDot1XConfigurationsResponse);

	/// Web service operation 'DeleteDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int DeleteDot1XConfiguration(_tds__DeleteDot1XConfiguration *tds__DeleteDot1XConfiguration, _tds__DeleteDot1XConfigurationResponse *tds__DeleteDot1XConfigurationResponse) { return this->DeleteDot1XConfiguration(NULL, NULL, tds__DeleteDot1XConfiguration, tds__DeleteDot1XConfigurationResponse); }
	virtual	int DeleteDot1XConfiguration(const char *endpoint, const char *soap_action, _tds__DeleteDot1XConfiguration *tds__DeleteDot1XConfiguration, _tds__DeleteDot1XConfigurationResponse *tds__DeleteDot1XConfigurationResponse);

	/// Web service operation 'GetDot11Capabilities' (returns error code or SOAP_OK)
	virtual	int GetDot11Capabilities(_tds__GetDot11Capabilities *tds__GetDot11Capabilities, _tds__GetDot11CapabilitiesResponse *tds__GetDot11CapabilitiesResponse) { return this->GetDot11Capabilities(NULL, NULL, tds__GetDot11Capabilities, tds__GetDot11CapabilitiesResponse); }
	virtual	int GetDot11Capabilities(const char *endpoint, const char *soap_action, _tds__GetDot11Capabilities *tds__GetDot11Capabilities, _tds__GetDot11CapabilitiesResponse *tds__GetDot11CapabilitiesResponse);

	/// Web service operation 'GetDot11Status' (returns error code or SOAP_OK)
	virtual	int GetDot11Status(_tds__GetDot11Status *tds__GetDot11Status, _tds__GetDot11StatusResponse *tds__GetDot11StatusResponse) { return this->GetDot11Status(NULL, NULL, tds__GetDot11Status, tds__GetDot11StatusResponse); }
	virtual	int GetDot11Status(const char *endpoint, const char *soap_action, _tds__GetDot11Status *tds__GetDot11Status, _tds__GetDot11StatusResponse *tds__GetDot11StatusResponse);

	/// Web service operation 'ScanAvailableDot11Networks' (returns error code or SOAP_OK)
	virtual	int ScanAvailableDot11Networks(_tds__ScanAvailableDot11Networks *tds__ScanAvailableDot11Networks, _tds__ScanAvailableDot11NetworksResponse *tds__ScanAvailableDot11NetworksResponse) { return this->ScanAvailableDot11Networks(NULL, NULL, tds__ScanAvailableDot11Networks, tds__ScanAvailableDot11NetworksResponse); }
	virtual	int ScanAvailableDot11Networks(const char *endpoint, const char *soap_action, _tds__ScanAvailableDot11Networks *tds__ScanAvailableDot11Networks, _tds__ScanAvailableDot11NetworksResponse *tds__ScanAvailableDot11NetworksResponse);

	/// Web service operation 'GetSystemUris' (returns error code or SOAP_OK)
	virtual	int GetSystemUris(_tds__GetSystemUris *tds__GetSystemUris, _tds__GetSystemUrisResponse *tds__GetSystemUrisResponse) { return this->GetSystemUris(NULL, NULL, tds__GetSystemUris, tds__GetSystemUrisResponse); }
	virtual	int GetSystemUris(const char *endpoint, const char *soap_action, _tds__GetSystemUris *tds__GetSystemUris, _tds__GetSystemUrisResponse *tds__GetSystemUrisResponse);

	/// Web service operation 'StartFirmwareUpgrade' (returns error code or SOAP_OK)
	virtual	int StartFirmwareUpgrade(_tds__StartFirmwareUpgrade *tds__StartFirmwareUpgrade, _tds__StartFirmwareUpgradeResponse *tds__StartFirmwareUpgradeResponse) { return this->StartFirmwareUpgrade(NULL, NULL, tds__StartFirmwareUpgrade, tds__StartFirmwareUpgradeResponse); }
	virtual	int StartFirmwareUpgrade(const char *endpoint, const char *soap_action, _tds__StartFirmwareUpgrade *tds__StartFirmwareUpgrade, _tds__StartFirmwareUpgradeResponse *tds__StartFirmwareUpgradeResponse);

	/// Web service operation 'StartSystemRestore' (returns error code or SOAP_OK)
	virtual	int StartSystemRestore(_tds__StartSystemRestore *tds__StartSystemRestore, _tds__StartSystemRestoreResponse *tds__StartSystemRestoreResponse) { return this->StartSystemRestore(NULL, NULL, tds__StartSystemRestore, tds__StartSystemRestoreResponse); }
	virtual	int StartSystemRestore(const char *endpoint, const char *soap_action, _tds__StartSystemRestore *tds__StartSystemRestore, _tds__StartSystemRestoreResponse *tds__StartSystemRestoreResponse);

	/// Web service operation 'GetServices' (returns error code or SOAP_OK)
	virtual	int GetServices_(_tds__GetServices *tds__GetServices, _tds__GetServicesResponse *tds__GetServicesResponse) { return this->GetServices_(NULL, NULL, tds__GetServices, tds__GetServicesResponse); }
	virtual	int GetServices_(const char *endpoint, const char *soap_action, _tds__GetServices *tds__GetServices, _tds__GetServicesResponse *tds__GetServicesResponse);

	/// Web service operation 'GetServiceCapabilities' (returns error code or SOAP_OK)
	virtual	int GetServiceCapabilities_(_tds__GetServiceCapabilities *tds__GetServiceCapabilities, _tds__GetServiceCapabilitiesResponse *tds__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities_(NULL, NULL, tds__GetServiceCapabilities, tds__GetServiceCapabilitiesResponse); }
	virtual	int GetServiceCapabilities_(const char *endpoint, const char *soap_action, _tds__GetServiceCapabilities *tds__GetServiceCapabilities, _tds__GetServiceCapabilitiesResponse *tds__GetServiceCapabilitiesResponse);

	/// Web service operation 'GetDeviceInformation' (returns error code or SOAP_OK)
	virtual	int GetDeviceInformation_(_tds__GetDeviceInformation *tds__GetDeviceInformation, _tds__GetDeviceInformationResponse *tds__GetDeviceInformationResponse) { return this->GetDeviceInformation_(NULL, NULL, tds__GetDeviceInformation, tds__GetDeviceInformationResponse); }
	virtual	int GetDeviceInformation_(const char *endpoint, const char *soap_action, _tds__GetDeviceInformation *tds__GetDeviceInformation, _tds__GetDeviceInformationResponse *tds__GetDeviceInformationResponse);

	/// Web service operation 'SetSystemDateAndTime' (returns error code or SOAP_OK)
	virtual	int SetSystemDateAndTime_(_tds__SetSystemDateAndTime *tds__SetSystemDateAndTime, _tds__SetSystemDateAndTimeResponse *tds__SetSystemDateAndTimeResponse) { return this->SetSystemDateAndTime_(NULL, NULL, tds__SetSystemDateAndTime, tds__SetSystemDateAndTimeResponse); }
	virtual	int SetSystemDateAndTime_(const char *endpoint, const char *soap_action, _tds__SetSystemDateAndTime *tds__SetSystemDateAndTime, _tds__SetSystemDateAndTimeResponse *tds__SetSystemDateAndTimeResponse);

	/// Web service operation 'GetSystemDateAndTime' (returns error code or SOAP_OK)
	virtual	int GetSystemDateAndTime_(_tds__GetSystemDateAndTime *tds__GetSystemDateAndTime, _tds__GetSystemDateAndTimeResponse *tds__GetSystemDateAndTimeResponse) { return this->GetSystemDateAndTime_(NULL, NULL, tds__GetSystemDateAndTime, tds__GetSystemDateAndTimeResponse); }
	virtual	int GetSystemDateAndTime_(const char *endpoint, const char *soap_action, _tds__GetSystemDateAndTime *tds__GetSystemDateAndTime, _tds__GetSystemDateAndTimeResponse *tds__GetSystemDateAndTimeResponse);

	/// Web service operation 'SetSystemFactoryDefault' (returns error code or SOAP_OK)
	virtual	int SetSystemFactoryDefault_(_tds__SetSystemFactoryDefault *tds__SetSystemFactoryDefault, _tds__SetSystemFactoryDefaultResponse *tds__SetSystemFactoryDefaultResponse) { return this->SetSystemFactoryDefault_(NULL, NULL, tds__SetSystemFactoryDefault, tds__SetSystemFactoryDefaultResponse); }
	virtual	int SetSystemFactoryDefault_(const char *endpoint, const char *soap_action, _tds__SetSystemFactoryDefault *tds__SetSystemFactoryDefault, _tds__SetSystemFactoryDefaultResponse *tds__SetSystemFactoryDefaultResponse);

	/// Web service operation 'UpgradeSystemFirmware' (returns error code or SOAP_OK)
	virtual	int UpgradeSystemFirmware_(_tds__UpgradeSystemFirmware *tds__UpgradeSystemFirmware, _tds__UpgradeSystemFirmwareResponse *tds__UpgradeSystemFirmwareResponse) { return this->UpgradeSystemFirmware_(NULL, NULL, tds__UpgradeSystemFirmware, tds__UpgradeSystemFirmwareResponse); }
	virtual	int UpgradeSystemFirmware_(const char *endpoint, const char *soap_action, _tds__UpgradeSystemFirmware *tds__UpgradeSystemFirmware, _tds__UpgradeSystemFirmwareResponse *tds__UpgradeSystemFirmwareResponse);

	/// Web service operation 'SystemReboot' (returns error code or SOAP_OK)
	virtual	int SystemReboot_(_tds__SystemReboot *tds__SystemReboot, _tds__SystemRebootResponse *tds__SystemRebootResponse) { return this->SystemReboot_(NULL, NULL, tds__SystemReboot, tds__SystemRebootResponse); }
	virtual	int SystemReboot_(const char *endpoint, const char *soap_action, _tds__SystemReboot *tds__SystemReboot, _tds__SystemRebootResponse *tds__SystemRebootResponse);

	/// Web service operation 'RestoreSystem' (returns error code or SOAP_OK)
	virtual	int RestoreSystem_(_tds__RestoreSystem *tds__RestoreSystem, _tds__RestoreSystemResponse *tds__RestoreSystemResponse) { return this->RestoreSystem_(NULL, NULL, tds__RestoreSystem, tds__RestoreSystemResponse); }
	virtual	int RestoreSystem_(const char *endpoint, const char *soap_action, _tds__RestoreSystem *tds__RestoreSystem, _tds__RestoreSystemResponse *tds__RestoreSystemResponse);

	/// Web service operation 'GetSystemBackup' (returns error code or SOAP_OK)
	virtual	int GetSystemBackup_(_tds__GetSystemBackup *tds__GetSystemBackup, _tds__GetSystemBackupResponse *tds__GetSystemBackupResponse) { return this->GetSystemBackup_(NULL, NULL, tds__GetSystemBackup, tds__GetSystemBackupResponse); }
	virtual	int GetSystemBackup_(const char *endpoint, const char *soap_action, _tds__GetSystemBackup *tds__GetSystemBackup, _tds__GetSystemBackupResponse *tds__GetSystemBackupResponse);

	/// Web service operation 'GetSystemLog' (returns error code or SOAP_OK)
	virtual	int GetSystemLog_(_tds__GetSystemLog *tds__GetSystemLog, _tds__GetSystemLogResponse *tds__GetSystemLogResponse) { return this->GetSystemLog_(NULL, NULL, tds__GetSystemLog, tds__GetSystemLogResponse); }
	virtual	int GetSystemLog_(const char *endpoint, const char *soap_action, _tds__GetSystemLog *tds__GetSystemLog, _tds__GetSystemLogResponse *tds__GetSystemLogResponse);

	/// Web service operation 'GetSystemSupportInformation' (returns error code or SOAP_OK)
	virtual	int GetSystemSupportInformation_(_tds__GetSystemSupportInformation *tds__GetSystemSupportInformation, _tds__GetSystemSupportInformationResponse *tds__GetSystemSupportInformationResponse) { return this->GetSystemSupportInformation_(NULL, NULL, tds__GetSystemSupportInformation, tds__GetSystemSupportInformationResponse); }
	virtual	int GetSystemSupportInformation_(const char *endpoint, const char *soap_action, _tds__GetSystemSupportInformation *tds__GetSystemSupportInformation, _tds__GetSystemSupportInformationResponse *tds__GetSystemSupportInformationResponse);

	/// Web service operation 'GetScopes' (returns error code or SOAP_OK)
	virtual	int GetScopes_(_tds__GetScopes *tds__GetScopes, _tds__GetScopesResponse *tds__GetScopesResponse) { return this->GetScopes_(NULL, NULL, tds__GetScopes, tds__GetScopesResponse); }
	virtual	int GetScopes_(const char *endpoint, const char *soap_action, _tds__GetScopes *tds__GetScopes, _tds__GetScopesResponse *tds__GetScopesResponse);

	/// Web service operation 'SetScopes' (returns error code or SOAP_OK)
	virtual	int SetScopes_(_tds__SetScopes *tds__SetScopes, _tds__SetScopesResponse *tds__SetScopesResponse) { return this->SetScopes_(NULL, NULL, tds__SetScopes, tds__SetScopesResponse); }
	virtual	int SetScopes_(const char *endpoint, const char *soap_action, _tds__SetScopes *tds__SetScopes, _tds__SetScopesResponse *tds__SetScopesResponse);

	/// Web service operation 'AddScopes' (returns error code or SOAP_OK)
	virtual	int AddScopes_(_tds__AddScopes *tds__AddScopes, _tds__AddScopesResponse *tds__AddScopesResponse) { return this->AddScopes_(NULL, NULL, tds__AddScopes, tds__AddScopesResponse); }
	virtual	int AddScopes_(const char *endpoint, const char *soap_action, _tds__AddScopes *tds__AddScopes, _tds__AddScopesResponse *tds__AddScopesResponse);

	/// Web service operation 'RemoveScopes' (returns error code or SOAP_OK)
	virtual	int RemoveScopes_(_tds__RemoveScopes *tds__RemoveScopes, _tds__RemoveScopesResponse *tds__RemoveScopesResponse) { return this->RemoveScopes_(NULL, NULL, tds__RemoveScopes, tds__RemoveScopesResponse); }
	virtual	int RemoveScopes_(const char *endpoint, const char *soap_action, _tds__RemoveScopes *tds__RemoveScopes, _tds__RemoveScopesResponse *tds__RemoveScopesResponse);

	/// Web service operation 'GetDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int GetDiscoveryMode_(_tds__GetDiscoveryMode *tds__GetDiscoveryMode, _tds__GetDiscoveryModeResponse *tds__GetDiscoveryModeResponse) { return this->GetDiscoveryMode_(NULL, NULL, tds__GetDiscoveryMode, tds__GetDiscoveryModeResponse); }
	virtual	int GetDiscoveryMode_(const char *endpoint, const char *soap_action, _tds__GetDiscoveryMode *tds__GetDiscoveryMode, _tds__GetDiscoveryModeResponse *tds__GetDiscoveryModeResponse);

	/// Web service operation 'SetDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int SetDiscoveryMode_(_tds__SetDiscoveryMode *tds__SetDiscoveryMode, _tds__SetDiscoveryModeResponse *tds__SetDiscoveryModeResponse) { return this->SetDiscoveryMode_(NULL, NULL, tds__SetDiscoveryMode, tds__SetDiscoveryModeResponse); }
	virtual	int SetDiscoveryMode_(const char *endpoint, const char *soap_action, _tds__SetDiscoveryMode *tds__SetDiscoveryMode, _tds__SetDiscoveryModeResponse *tds__SetDiscoveryModeResponse);

	/// Web service operation 'GetRemoteDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int GetRemoteDiscoveryMode_(_tds__GetRemoteDiscoveryMode *tds__GetRemoteDiscoveryMode, _tds__GetRemoteDiscoveryModeResponse *tds__GetRemoteDiscoveryModeResponse) { return this->GetRemoteDiscoveryMode_(NULL, NULL, tds__GetRemoteDiscoveryMode, tds__GetRemoteDiscoveryModeResponse); }
	virtual	int GetRemoteDiscoveryMode_(const char *endpoint, const char *soap_action, _tds__GetRemoteDiscoveryMode *tds__GetRemoteDiscoveryMode, _tds__GetRemoteDiscoveryModeResponse *tds__GetRemoteDiscoveryModeResponse);

	/// Web service operation 'SetRemoteDiscoveryMode' (returns error code or SOAP_OK)
	virtual	int SetRemoteDiscoveryMode_(_tds__SetRemoteDiscoveryMode *tds__SetRemoteDiscoveryMode, _tds__SetRemoteDiscoveryModeResponse *tds__SetRemoteDiscoveryModeResponse) { return this->SetRemoteDiscoveryMode_(NULL, NULL, tds__SetRemoteDiscoveryMode, tds__SetRemoteDiscoveryModeResponse); }
	virtual	int SetRemoteDiscoveryMode_(const char *endpoint, const char *soap_action, _tds__SetRemoteDiscoveryMode *tds__SetRemoteDiscoveryMode, _tds__SetRemoteDiscoveryModeResponse *tds__SetRemoteDiscoveryModeResponse);

	/// Web service operation 'GetDPAddresses' (returns error code or SOAP_OK)
	virtual	int GetDPAddresses_(_tds__GetDPAddresses *tds__GetDPAddresses, _tds__GetDPAddressesResponse *tds__GetDPAddressesResponse) { return this->GetDPAddresses_(NULL, NULL, tds__GetDPAddresses, tds__GetDPAddressesResponse); }
	virtual	int GetDPAddresses_(const char *endpoint, const char *soap_action, _tds__GetDPAddresses *tds__GetDPAddresses, _tds__GetDPAddressesResponse *tds__GetDPAddressesResponse);

	/// Web service operation 'GetEndpointReference' (returns error code or SOAP_OK)
	virtual	int GetEndpointReference_(_tds__GetEndpointReference *tds__GetEndpointReference, _tds__GetEndpointReferenceResponse *tds__GetEndpointReferenceResponse) { return this->GetEndpointReference_(NULL, NULL, tds__GetEndpointReference, tds__GetEndpointReferenceResponse); }
	virtual	int GetEndpointReference_(const char *endpoint, const char *soap_action, _tds__GetEndpointReference *tds__GetEndpointReference, _tds__GetEndpointReferenceResponse *tds__GetEndpointReferenceResponse);

	/// Web service operation 'GetRemoteUser' (returns error code or SOAP_OK)
	virtual	int GetRemoteUser_(_tds__GetRemoteUser *tds__GetRemoteUser, _tds__GetRemoteUserResponse *tds__GetRemoteUserResponse) { return this->GetRemoteUser_(NULL, NULL, tds__GetRemoteUser, tds__GetRemoteUserResponse); }
	virtual	int GetRemoteUser_(const char *endpoint, const char *soap_action, _tds__GetRemoteUser *tds__GetRemoteUser, _tds__GetRemoteUserResponse *tds__GetRemoteUserResponse);

	/// Web service operation 'SetRemoteUser' (returns error code or SOAP_OK)
	virtual	int SetRemoteUser_(_tds__SetRemoteUser *tds__SetRemoteUser, _tds__SetRemoteUserResponse *tds__SetRemoteUserResponse) { return this->SetRemoteUser_(NULL, NULL, tds__SetRemoteUser, tds__SetRemoteUserResponse); }
	virtual	int SetRemoteUser_(const char *endpoint, const char *soap_action, _tds__SetRemoteUser *tds__SetRemoteUser, _tds__SetRemoteUserResponse *tds__SetRemoteUserResponse);

	/// Web service operation 'GetUsers' (returns error code or SOAP_OK)
	virtual	int GetUsers_(_tds__GetUsers *tds__GetUsers, _tds__GetUsersResponse *tds__GetUsersResponse) { return this->GetUsers_(NULL, NULL, tds__GetUsers, tds__GetUsersResponse); }
	virtual	int GetUsers_(const char *endpoint, const char *soap_action, _tds__GetUsers *tds__GetUsers, _tds__GetUsersResponse *tds__GetUsersResponse);

	/// Web service operation 'CreateUsers' (returns error code or SOAP_OK)
	virtual	int CreateUsers_(_tds__CreateUsers *tds__CreateUsers, _tds__CreateUsersResponse *tds__CreateUsersResponse) { return this->CreateUsers_(NULL, NULL, tds__CreateUsers, tds__CreateUsersResponse); }
	virtual	int CreateUsers_(const char *endpoint, const char *soap_action, _tds__CreateUsers *tds__CreateUsers, _tds__CreateUsersResponse *tds__CreateUsersResponse);

	/// Web service operation 'DeleteUsers' (returns error code or SOAP_OK)
	virtual	int DeleteUsers_(_tds__DeleteUsers *tds__DeleteUsers, _tds__DeleteUsersResponse *tds__DeleteUsersResponse) { return this->DeleteUsers_(NULL, NULL, tds__DeleteUsers, tds__DeleteUsersResponse); }
	virtual	int DeleteUsers_(const char *endpoint, const char *soap_action, _tds__DeleteUsers *tds__DeleteUsers, _tds__DeleteUsersResponse *tds__DeleteUsersResponse);

	/// Web service operation 'SetUser' (returns error code or SOAP_OK)
	virtual	int SetUser_(_tds__SetUser *tds__SetUser, _tds__SetUserResponse *tds__SetUserResponse) { return this->SetUser_(NULL, NULL, tds__SetUser, tds__SetUserResponse); }
	virtual	int SetUser_(const char *endpoint, const char *soap_action, _tds__SetUser *tds__SetUser, _tds__SetUserResponse *tds__SetUserResponse);

	/// Web service operation 'GetWsdlUrl' (returns error code or SOAP_OK)
	virtual	int GetWsdlUrl_(_tds__GetWsdlUrl *tds__GetWsdlUrl, _tds__GetWsdlUrlResponse *tds__GetWsdlUrlResponse) { return this->GetWsdlUrl_(NULL, NULL, tds__GetWsdlUrl, tds__GetWsdlUrlResponse); }
	virtual	int GetWsdlUrl_(const char *endpoint, const char *soap_action, _tds__GetWsdlUrl *tds__GetWsdlUrl, _tds__GetWsdlUrlResponse *tds__GetWsdlUrlResponse);

	/// Web service operation 'GetCapabilities' (returns error code or SOAP_OK)
	virtual	int GetCapabilities_(_tds__GetCapabilities *tds__GetCapabilities, _tds__GetCapabilitiesResponse *tds__GetCapabilitiesResponse) { return this->GetCapabilities_(NULL, NULL, tds__GetCapabilities, tds__GetCapabilitiesResponse); }
	virtual	int GetCapabilities_(const char *endpoint, const char *soap_action, _tds__GetCapabilities *tds__GetCapabilities, _tds__GetCapabilitiesResponse *tds__GetCapabilitiesResponse);

	/// Web service operation 'SetDPAddresses' (returns error code or SOAP_OK)
	virtual	int SetDPAddresses_(_tds__SetDPAddresses *tds__SetDPAddresses, _tds__SetDPAddressesResponse *tds__SetDPAddressesResponse) { return this->SetDPAddresses_(NULL, NULL, tds__SetDPAddresses, tds__SetDPAddressesResponse); }
	virtual	int SetDPAddresses_(const char *endpoint, const char *soap_action, _tds__SetDPAddresses *tds__SetDPAddresses, _tds__SetDPAddressesResponse *tds__SetDPAddressesResponse);

	/// Web service operation 'GetHostname' (returns error code or SOAP_OK)
	virtual	int GetHostname_(_tds__GetHostname *tds__GetHostname, _tds__GetHostnameResponse *tds__GetHostnameResponse) { return this->GetHostname_(NULL, NULL, tds__GetHostname, tds__GetHostnameResponse); }
	virtual	int GetHostname_(const char *endpoint, const char *soap_action, _tds__GetHostname *tds__GetHostname, _tds__GetHostnameResponse *tds__GetHostnameResponse);

	/// Web service operation 'SetHostname' (returns error code or SOAP_OK)
	virtual	int SetHostname_(_tds__SetHostname *tds__SetHostname, _tds__SetHostnameResponse *tds__SetHostnameResponse) { return this->SetHostname_(NULL, NULL, tds__SetHostname, tds__SetHostnameResponse); }
	virtual	int SetHostname_(const char *endpoint, const char *soap_action, _tds__SetHostname *tds__SetHostname, _tds__SetHostnameResponse *tds__SetHostnameResponse);

	/// Web service operation 'SetHostnameFromDHCP' (returns error code or SOAP_OK)
	virtual	int SetHostnameFromDHCP_(_tds__SetHostnameFromDHCP *tds__SetHostnameFromDHCP, _tds__SetHostnameFromDHCPResponse *tds__SetHostnameFromDHCPResponse) { return this->SetHostnameFromDHCP_(NULL, NULL, tds__SetHostnameFromDHCP, tds__SetHostnameFromDHCPResponse); }
	virtual	int SetHostnameFromDHCP_(const char *endpoint, const char *soap_action, _tds__SetHostnameFromDHCP *tds__SetHostnameFromDHCP, _tds__SetHostnameFromDHCPResponse *tds__SetHostnameFromDHCPResponse);

	/// Web service operation 'GetDNS' (returns error code or SOAP_OK)
	virtual	int GetDNS_(_tds__GetDNS *tds__GetDNS, _tds__GetDNSResponse *tds__GetDNSResponse) { return this->GetDNS_(NULL, NULL, tds__GetDNS, tds__GetDNSResponse); }
	virtual	int GetDNS_(const char *endpoint, const char *soap_action, _tds__GetDNS *tds__GetDNS, _tds__GetDNSResponse *tds__GetDNSResponse);

	/// Web service operation 'SetDNS' (returns error code or SOAP_OK)
	virtual	int SetDNS_(_tds__SetDNS *tds__SetDNS, _tds__SetDNSResponse *tds__SetDNSResponse) { return this->SetDNS_(NULL, NULL, tds__SetDNS, tds__SetDNSResponse); }
	virtual	int SetDNS_(const char *endpoint, const char *soap_action, _tds__SetDNS *tds__SetDNS, _tds__SetDNSResponse *tds__SetDNSResponse);

	/// Web service operation 'GetNTP' (returns error code or SOAP_OK)
	virtual	int GetNTP_(_tds__GetNTP *tds__GetNTP, _tds__GetNTPResponse *tds__GetNTPResponse) { return this->GetNTP_(NULL, NULL, tds__GetNTP, tds__GetNTPResponse); }
	virtual	int GetNTP_(const char *endpoint, const char *soap_action, _tds__GetNTP *tds__GetNTP, _tds__GetNTPResponse *tds__GetNTPResponse);

	/// Web service operation 'SetNTP' (returns error code or SOAP_OK)
	virtual	int SetNTP_(_tds__SetNTP *tds__SetNTP, _tds__SetNTPResponse *tds__SetNTPResponse) { return this->SetNTP_(NULL, NULL, tds__SetNTP, tds__SetNTPResponse); }
	virtual	int SetNTP_(const char *endpoint, const char *soap_action, _tds__SetNTP *tds__SetNTP, _tds__SetNTPResponse *tds__SetNTPResponse);

	/// Web service operation 'GetDynamicDNS' (returns error code or SOAP_OK)
	virtual	int GetDynamicDNS_(_tds__GetDynamicDNS *tds__GetDynamicDNS, _tds__GetDynamicDNSResponse *tds__GetDynamicDNSResponse) { return this->GetDynamicDNS_(NULL, NULL, tds__GetDynamicDNS, tds__GetDynamicDNSResponse); }
	virtual	int GetDynamicDNS_(const char *endpoint, const char *soap_action, _tds__GetDynamicDNS *tds__GetDynamicDNS, _tds__GetDynamicDNSResponse *tds__GetDynamicDNSResponse);

	/// Web service operation 'SetDynamicDNS' (returns error code or SOAP_OK)
	virtual	int SetDynamicDNS_(_tds__SetDynamicDNS *tds__SetDynamicDNS, _tds__SetDynamicDNSResponse *tds__SetDynamicDNSResponse) { return this->SetDynamicDNS_(NULL, NULL, tds__SetDynamicDNS, tds__SetDynamicDNSResponse); }
	virtual	int SetDynamicDNS_(const char *endpoint, const char *soap_action, _tds__SetDynamicDNS *tds__SetDynamicDNS, _tds__SetDynamicDNSResponse *tds__SetDynamicDNSResponse);

	/// Web service operation 'GetNetworkInterfaces' (returns error code or SOAP_OK)
	virtual	int GetNetworkInterfaces_(_tds__GetNetworkInterfaces *tds__GetNetworkInterfaces, _tds__GetNetworkInterfacesResponse *tds__GetNetworkInterfacesResponse) { return this->GetNetworkInterfaces_(NULL, NULL, tds__GetNetworkInterfaces, tds__GetNetworkInterfacesResponse); }
	virtual	int GetNetworkInterfaces_(const char *endpoint, const char *soap_action, _tds__GetNetworkInterfaces *tds__GetNetworkInterfaces, _tds__GetNetworkInterfacesResponse *tds__GetNetworkInterfacesResponse);

	/// Web service operation 'SetNetworkInterfaces' (returns error code or SOAP_OK)
	virtual	int SetNetworkInterfaces_(_tds__SetNetworkInterfaces *tds__SetNetworkInterfaces, _tds__SetNetworkInterfacesResponse *tds__SetNetworkInterfacesResponse) { return this->SetNetworkInterfaces_(NULL, NULL, tds__SetNetworkInterfaces, tds__SetNetworkInterfacesResponse); }
	virtual	int SetNetworkInterfaces_(const char *endpoint, const char *soap_action, _tds__SetNetworkInterfaces *tds__SetNetworkInterfaces, _tds__SetNetworkInterfacesResponse *tds__SetNetworkInterfacesResponse);

	/// Web service operation 'GetNetworkProtocols' (returns error code or SOAP_OK)
	virtual	int GetNetworkProtocols_(_tds__GetNetworkProtocols *tds__GetNetworkProtocols, _tds__GetNetworkProtocolsResponse *tds__GetNetworkProtocolsResponse) { return this->GetNetworkProtocols_(NULL, NULL, tds__GetNetworkProtocols, tds__GetNetworkProtocolsResponse); }
	virtual	int GetNetworkProtocols_(const char *endpoint, const char *soap_action, _tds__GetNetworkProtocols *tds__GetNetworkProtocols, _tds__GetNetworkProtocolsResponse *tds__GetNetworkProtocolsResponse);

	/// Web service operation 'SetNetworkProtocols' (returns error code or SOAP_OK)
	virtual	int SetNetworkProtocols_(_tds__SetNetworkProtocols *tds__SetNetworkProtocols, _tds__SetNetworkProtocolsResponse *tds__SetNetworkProtocolsResponse) { return this->SetNetworkProtocols_(NULL, NULL, tds__SetNetworkProtocols, tds__SetNetworkProtocolsResponse); }
	virtual	int SetNetworkProtocols_(const char *endpoint, const char *soap_action, _tds__SetNetworkProtocols *tds__SetNetworkProtocols, _tds__SetNetworkProtocolsResponse *tds__SetNetworkProtocolsResponse);

	/// Web service operation 'GetNetworkDefaultGateway' (returns error code or SOAP_OK)
	virtual	int GetNetworkDefaultGateway_(_tds__GetNetworkDefaultGateway *tds__GetNetworkDefaultGateway, _tds__GetNetworkDefaultGatewayResponse *tds__GetNetworkDefaultGatewayResponse) { return this->GetNetworkDefaultGateway_(NULL, NULL, tds__GetNetworkDefaultGateway, tds__GetNetworkDefaultGatewayResponse); }
	virtual	int GetNetworkDefaultGateway_(const char *endpoint, const char *soap_action, _tds__GetNetworkDefaultGateway *tds__GetNetworkDefaultGateway, _tds__GetNetworkDefaultGatewayResponse *tds__GetNetworkDefaultGatewayResponse);

	/// Web service operation 'SetNetworkDefaultGateway' (returns error code or SOAP_OK)
	virtual	int SetNetworkDefaultGateway_(_tds__SetNetworkDefaultGateway *tds__SetNetworkDefaultGateway, _tds__SetNetworkDefaultGatewayResponse *tds__SetNetworkDefaultGatewayResponse) { return this->SetNetworkDefaultGateway_(NULL, NULL, tds__SetNetworkDefaultGateway, tds__SetNetworkDefaultGatewayResponse); }
	virtual	int SetNetworkDefaultGateway_(const char *endpoint, const char *soap_action, _tds__SetNetworkDefaultGateway *tds__SetNetworkDefaultGateway, _tds__SetNetworkDefaultGatewayResponse *tds__SetNetworkDefaultGatewayResponse);

	/// Web service operation 'GetZeroConfiguration' (returns error code or SOAP_OK)
	virtual	int GetZeroConfiguration_(_tds__GetZeroConfiguration *tds__GetZeroConfiguration, _tds__GetZeroConfigurationResponse *tds__GetZeroConfigurationResponse) { return this->GetZeroConfiguration_(NULL, NULL, tds__GetZeroConfiguration, tds__GetZeroConfigurationResponse); }
	virtual	int GetZeroConfiguration_(const char *endpoint, const char *soap_action, _tds__GetZeroConfiguration *tds__GetZeroConfiguration, _tds__GetZeroConfigurationResponse *tds__GetZeroConfigurationResponse);

	/// Web service operation 'SetZeroConfiguration' (returns error code or SOAP_OK)
	virtual	int SetZeroConfiguration_(_tds__SetZeroConfiguration *tds__SetZeroConfiguration, _tds__SetZeroConfigurationResponse *tds__SetZeroConfigurationResponse) { return this->SetZeroConfiguration_(NULL, NULL, tds__SetZeroConfiguration, tds__SetZeroConfigurationResponse); }
	virtual	int SetZeroConfiguration_(const char *endpoint, const char *soap_action, _tds__SetZeroConfiguration *tds__SetZeroConfiguration, _tds__SetZeroConfigurationResponse *tds__SetZeroConfigurationResponse);

	/// Web service operation 'GetIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int GetIPAddressFilter_(_tds__GetIPAddressFilter *tds__GetIPAddressFilter, _tds__GetIPAddressFilterResponse *tds__GetIPAddressFilterResponse) { return this->GetIPAddressFilter_(NULL, NULL, tds__GetIPAddressFilter, tds__GetIPAddressFilterResponse); }
	virtual	int GetIPAddressFilter_(const char *endpoint, const char *soap_action, _tds__GetIPAddressFilter *tds__GetIPAddressFilter, _tds__GetIPAddressFilterResponse *tds__GetIPAddressFilterResponse);

	/// Web service operation 'SetIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int SetIPAddressFilter_(_tds__SetIPAddressFilter *tds__SetIPAddressFilter, _tds__SetIPAddressFilterResponse *tds__SetIPAddressFilterResponse) { return this->SetIPAddressFilter_(NULL, NULL, tds__SetIPAddressFilter, tds__SetIPAddressFilterResponse); }
	virtual	int SetIPAddressFilter_(const char *endpoint, const char *soap_action, _tds__SetIPAddressFilter *tds__SetIPAddressFilter, _tds__SetIPAddressFilterResponse *tds__SetIPAddressFilterResponse);

	/// Web service operation 'AddIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int AddIPAddressFilter_(_tds__AddIPAddressFilter *tds__AddIPAddressFilter, _tds__AddIPAddressFilterResponse *tds__AddIPAddressFilterResponse) { return this->AddIPAddressFilter_(NULL, NULL, tds__AddIPAddressFilter, tds__AddIPAddressFilterResponse); }
	virtual	int AddIPAddressFilter_(const char *endpoint, const char *soap_action, _tds__AddIPAddressFilter *tds__AddIPAddressFilter, _tds__AddIPAddressFilterResponse *tds__AddIPAddressFilterResponse);

	/// Web service operation 'RemoveIPAddressFilter' (returns error code or SOAP_OK)
	virtual	int RemoveIPAddressFilter_(_tds__RemoveIPAddressFilter *tds__RemoveIPAddressFilter, _tds__RemoveIPAddressFilterResponse *tds__RemoveIPAddressFilterResponse) { return this->RemoveIPAddressFilter_(NULL, NULL, tds__RemoveIPAddressFilter, tds__RemoveIPAddressFilterResponse); }
	virtual	int RemoveIPAddressFilter_(const char *endpoint, const char *soap_action, _tds__RemoveIPAddressFilter *tds__RemoveIPAddressFilter, _tds__RemoveIPAddressFilterResponse *tds__RemoveIPAddressFilterResponse);

	/// Web service operation 'GetAccessPolicy' (returns error code or SOAP_OK)
	virtual	int GetAccessPolicy_(_tds__GetAccessPolicy *tds__GetAccessPolicy, _tds__GetAccessPolicyResponse *tds__GetAccessPolicyResponse) { return this->GetAccessPolicy_(NULL, NULL, tds__GetAccessPolicy, tds__GetAccessPolicyResponse); }
	virtual	int GetAccessPolicy_(const char *endpoint, const char *soap_action, _tds__GetAccessPolicy *tds__GetAccessPolicy, _tds__GetAccessPolicyResponse *tds__GetAccessPolicyResponse);

	/// Web service operation 'SetAccessPolicy' (returns error code or SOAP_OK)
	virtual	int SetAccessPolicy_(_tds__SetAccessPolicy *tds__SetAccessPolicy, _tds__SetAccessPolicyResponse *tds__SetAccessPolicyResponse) { return this->SetAccessPolicy_(NULL, NULL, tds__SetAccessPolicy, tds__SetAccessPolicyResponse); }
	virtual	int SetAccessPolicy_(const char *endpoint, const char *soap_action, _tds__SetAccessPolicy *tds__SetAccessPolicy, _tds__SetAccessPolicyResponse *tds__SetAccessPolicyResponse);

	/// Web service operation 'CreateCertificate' (returns error code or SOAP_OK)
	virtual	int CreateCertificate_(_tds__CreateCertificate *tds__CreateCertificate, _tds__CreateCertificateResponse *tds__CreateCertificateResponse) { return this->CreateCertificate_(NULL, NULL, tds__CreateCertificate, tds__CreateCertificateResponse); }
	virtual	int CreateCertificate_(const char *endpoint, const char *soap_action, _tds__CreateCertificate *tds__CreateCertificate, _tds__CreateCertificateResponse *tds__CreateCertificateResponse);

	/// Web service operation 'GetCertificates' (returns error code or SOAP_OK)
	virtual	int GetCertificates_(_tds__GetCertificates *tds__GetCertificates, _tds__GetCertificatesResponse *tds__GetCertificatesResponse) { return this->GetCertificates_(NULL, NULL, tds__GetCertificates, tds__GetCertificatesResponse); }
	virtual	int GetCertificates_(const char *endpoint, const char *soap_action, _tds__GetCertificates *tds__GetCertificates, _tds__GetCertificatesResponse *tds__GetCertificatesResponse);

	/// Web service operation 'GetCertificatesStatus' (returns error code or SOAP_OK)
	virtual	int GetCertificatesStatus_(_tds__GetCertificatesStatus *tds__GetCertificatesStatus, _tds__GetCertificatesStatusResponse *tds__GetCertificatesStatusResponse) { return this->GetCertificatesStatus_(NULL, NULL, tds__GetCertificatesStatus, tds__GetCertificatesStatusResponse); }
	virtual	int GetCertificatesStatus_(const char *endpoint, const char *soap_action, _tds__GetCertificatesStatus *tds__GetCertificatesStatus, _tds__GetCertificatesStatusResponse *tds__GetCertificatesStatusResponse);

	/// Web service operation 'SetCertificatesStatus' (returns error code or SOAP_OK)
	virtual	int SetCertificatesStatus_(_tds__SetCertificatesStatus *tds__SetCertificatesStatus, _tds__SetCertificatesStatusResponse *tds__SetCertificatesStatusResponse) { return this->SetCertificatesStatus_(NULL, NULL, tds__SetCertificatesStatus, tds__SetCertificatesStatusResponse); }
	virtual	int SetCertificatesStatus_(const char *endpoint, const char *soap_action, _tds__SetCertificatesStatus *tds__SetCertificatesStatus, _tds__SetCertificatesStatusResponse *tds__SetCertificatesStatusResponse);

	/// Web service operation 'DeleteCertificates' (returns error code or SOAP_OK)
	virtual	int DeleteCertificates_(_tds__DeleteCertificates *tds__DeleteCertificates, _tds__DeleteCertificatesResponse *tds__DeleteCertificatesResponse) { return this->DeleteCertificates_(NULL, NULL, tds__DeleteCertificates, tds__DeleteCertificatesResponse); }
	virtual	int DeleteCertificates_(const char *endpoint, const char *soap_action, _tds__DeleteCertificates *tds__DeleteCertificates, _tds__DeleteCertificatesResponse *tds__DeleteCertificatesResponse);

	/// Web service operation 'GetPkcs10Request' (returns error code or SOAP_OK)
	virtual	int GetPkcs10Request_(_tds__GetPkcs10Request *tds__GetPkcs10Request, _tds__GetPkcs10RequestResponse *tds__GetPkcs10RequestResponse) { return this->GetPkcs10Request_(NULL, NULL, tds__GetPkcs10Request, tds__GetPkcs10RequestResponse); }
	virtual	int GetPkcs10Request_(const char *endpoint, const char *soap_action, _tds__GetPkcs10Request *tds__GetPkcs10Request, _tds__GetPkcs10RequestResponse *tds__GetPkcs10RequestResponse);

	/// Web service operation 'LoadCertificates' (returns error code or SOAP_OK)
	virtual	int LoadCertificates_(_tds__LoadCertificates *tds__LoadCertificates, _tds__LoadCertificatesResponse *tds__LoadCertificatesResponse) { return this->LoadCertificates_(NULL, NULL, tds__LoadCertificates, tds__LoadCertificatesResponse); }
	virtual	int LoadCertificates_(const char *endpoint, const char *soap_action, _tds__LoadCertificates *tds__LoadCertificates, _tds__LoadCertificatesResponse *tds__LoadCertificatesResponse);

	/// Web service operation 'GetClientCertificateMode' (returns error code or SOAP_OK)
	virtual	int GetClientCertificateMode_(_tds__GetClientCertificateMode *tds__GetClientCertificateMode, _tds__GetClientCertificateModeResponse *tds__GetClientCertificateModeResponse) { return this->GetClientCertificateMode_(NULL, NULL, tds__GetClientCertificateMode, tds__GetClientCertificateModeResponse); }
	virtual	int GetClientCertificateMode_(const char *endpoint, const char *soap_action, _tds__GetClientCertificateMode *tds__GetClientCertificateMode, _tds__GetClientCertificateModeResponse *tds__GetClientCertificateModeResponse);

	/// Web service operation 'SetClientCertificateMode' (returns error code or SOAP_OK)
	virtual	int SetClientCertificateMode_(_tds__SetClientCertificateMode *tds__SetClientCertificateMode, _tds__SetClientCertificateModeResponse *tds__SetClientCertificateModeResponse) { return this->SetClientCertificateMode_(NULL, NULL, tds__SetClientCertificateMode, tds__SetClientCertificateModeResponse); }
	virtual	int SetClientCertificateMode_(const char *endpoint, const char *soap_action, _tds__SetClientCertificateMode *tds__SetClientCertificateMode, _tds__SetClientCertificateModeResponse *tds__SetClientCertificateModeResponse);

	/// Web service operation 'GetRelayOutputs' (returns error code or SOAP_OK)
	virtual	int GetRelayOutputs_(_tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse *tds__GetRelayOutputsResponse) { return this->GetRelayOutputs_(NULL, NULL, tds__GetRelayOutputs, tds__GetRelayOutputsResponse); }
	virtual	int GetRelayOutputs_(const char *endpoint, const char *soap_action, _tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse *tds__GetRelayOutputsResponse);

	/// Web service operation 'SetRelayOutputSettings' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputSettings_(_tds__SetRelayOutputSettings *tds__SetRelayOutputSettings, _tds__SetRelayOutputSettingsResponse *tds__SetRelayOutputSettingsResponse) { return this->SetRelayOutputSettings_(NULL, NULL, tds__SetRelayOutputSettings, tds__SetRelayOutputSettingsResponse); }
	virtual	int SetRelayOutputSettings_(const char *endpoint, const char *soap_action, _tds__SetRelayOutputSettings *tds__SetRelayOutputSettings, _tds__SetRelayOutputSettingsResponse *tds__SetRelayOutputSettingsResponse);

	/// Web service operation 'SetRelayOutputState' (returns error code or SOAP_OK)
	virtual	int SetRelayOutputState_(_tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse *tds__SetRelayOutputStateResponse) { return this->SetRelayOutputState_(NULL, NULL, tds__SetRelayOutputState, tds__SetRelayOutputStateResponse); }
	virtual	int SetRelayOutputState_(const char *endpoint, const char *soap_action, _tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse *tds__SetRelayOutputStateResponse);

	/// Web service operation 'SendAuxiliaryCommand' (returns error code or SOAP_OK)
	virtual	int SendAuxiliaryCommand_(_tds__SendAuxiliaryCommand *tds__SendAuxiliaryCommand, _tds__SendAuxiliaryCommandResponse *tds__SendAuxiliaryCommandResponse) { return this->SendAuxiliaryCommand_(NULL, NULL, tds__SendAuxiliaryCommand, tds__SendAuxiliaryCommandResponse); }
	virtual	int SendAuxiliaryCommand_(const char *endpoint, const char *soap_action, _tds__SendAuxiliaryCommand *tds__SendAuxiliaryCommand, _tds__SendAuxiliaryCommandResponse *tds__SendAuxiliaryCommandResponse);

	/// Web service operation 'GetCACertificates' (returns error code or SOAP_OK)
	virtual	int GetCACertificates_(_tds__GetCACertificates *tds__GetCACertificates, _tds__GetCACertificatesResponse *tds__GetCACertificatesResponse) { return this->GetCACertificates_(NULL, NULL, tds__GetCACertificates, tds__GetCACertificatesResponse); }
	virtual	int GetCACertificates_(const char *endpoint, const char *soap_action, _tds__GetCACertificates *tds__GetCACertificates, _tds__GetCACertificatesResponse *tds__GetCACertificatesResponse);

	/// Web service operation 'LoadCertificateWithPrivateKey' (returns error code or SOAP_OK)
	virtual	int LoadCertificateWithPrivateKey_(_tds__LoadCertificateWithPrivateKey *tds__LoadCertificateWithPrivateKey, _tds__LoadCertificateWithPrivateKeyResponse *tds__LoadCertificateWithPrivateKeyResponse) { return this->LoadCertificateWithPrivateKey_(NULL, NULL, tds__LoadCertificateWithPrivateKey, tds__LoadCertificateWithPrivateKeyResponse); }
	virtual	int LoadCertificateWithPrivateKey_(const char *endpoint, const char *soap_action, _tds__LoadCertificateWithPrivateKey *tds__LoadCertificateWithPrivateKey, _tds__LoadCertificateWithPrivateKeyResponse *tds__LoadCertificateWithPrivateKeyResponse);

	/// Web service operation 'GetCertificateInformation' (returns error code or SOAP_OK)
	virtual	int GetCertificateInformation_(_tds__GetCertificateInformation *tds__GetCertificateInformation, _tds__GetCertificateInformationResponse *tds__GetCertificateInformationResponse) { return this->GetCertificateInformation_(NULL, NULL, tds__GetCertificateInformation, tds__GetCertificateInformationResponse); }
	virtual	int GetCertificateInformation_(const char *endpoint, const char *soap_action, _tds__GetCertificateInformation *tds__GetCertificateInformation, _tds__GetCertificateInformationResponse *tds__GetCertificateInformationResponse);

	/// Web service operation 'LoadCACertificates' (returns error code or SOAP_OK)
	virtual	int LoadCACertificates_(_tds__LoadCACertificates *tds__LoadCACertificates, _tds__LoadCACertificatesResponse *tds__LoadCACertificatesResponse) { return this->LoadCACertificates_(NULL, NULL, tds__LoadCACertificates, tds__LoadCACertificatesResponse); }
	virtual	int LoadCACertificates_(const char *endpoint, const char *soap_action, _tds__LoadCACertificates *tds__LoadCACertificates, _tds__LoadCACertificatesResponse *tds__LoadCACertificatesResponse);

	/// Web service operation 'CreateDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int CreateDot1XConfiguration_(_tds__CreateDot1XConfiguration *tds__CreateDot1XConfiguration, _tds__CreateDot1XConfigurationResponse *tds__CreateDot1XConfigurationResponse) { return this->CreateDot1XConfiguration_(NULL, NULL, tds__CreateDot1XConfiguration, tds__CreateDot1XConfigurationResponse); }
	virtual	int CreateDot1XConfiguration_(const char *endpoint, const char *soap_action, _tds__CreateDot1XConfiguration *tds__CreateDot1XConfiguration, _tds__CreateDot1XConfigurationResponse *tds__CreateDot1XConfigurationResponse);

	/// Web service operation 'SetDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int SetDot1XConfiguration_(_tds__SetDot1XConfiguration *tds__SetDot1XConfiguration, _tds__SetDot1XConfigurationResponse *tds__SetDot1XConfigurationResponse) { return this->SetDot1XConfiguration_(NULL, NULL, tds__SetDot1XConfiguration, tds__SetDot1XConfigurationResponse); }
	virtual	int SetDot1XConfiguration_(const char *endpoint, const char *soap_action, _tds__SetDot1XConfiguration *tds__SetDot1XConfiguration, _tds__SetDot1XConfigurationResponse *tds__SetDot1XConfigurationResponse);

	/// Web service operation 'GetDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int GetDot1XConfiguration_(_tds__GetDot1XConfiguration *tds__GetDot1XConfiguration, _tds__GetDot1XConfigurationResponse *tds__GetDot1XConfigurationResponse) { return this->GetDot1XConfiguration_(NULL, NULL, tds__GetDot1XConfiguration, tds__GetDot1XConfigurationResponse); }
	virtual	int GetDot1XConfiguration_(const char *endpoint, const char *soap_action, _tds__GetDot1XConfiguration *tds__GetDot1XConfiguration, _tds__GetDot1XConfigurationResponse *tds__GetDot1XConfigurationResponse);

	/// Web service operation 'GetDot1XConfigurations' (returns error code or SOAP_OK)
	virtual	int GetDot1XConfigurations_(_tds__GetDot1XConfigurations *tds__GetDot1XConfigurations, _tds__GetDot1XConfigurationsResponse *tds__GetDot1XConfigurationsResponse) { return this->GetDot1XConfigurations_(NULL, NULL, tds__GetDot1XConfigurations, tds__GetDot1XConfigurationsResponse); }
	virtual	int GetDot1XConfigurations_(const char *endpoint, const char *soap_action, _tds__GetDot1XConfigurations *tds__GetDot1XConfigurations, _tds__GetDot1XConfigurationsResponse *tds__GetDot1XConfigurationsResponse);

	/// Web service operation 'DeleteDot1XConfiguration' (returns error code or SOAP_OK)
	virtual	int DeleteDot1XConfiguration_(_tds__DeleteDot1XConfiguration *tds__DeleteDot1XConfiguration, _tds__DeleteDot1XConfigurationResponse *tds__DeleteDot1XConfigurationResponse) { return this->DeleteDot1XConfiguration_(NULL, NULL, tds__DeleteDot1XConfiguration, tds__DeleteDot1XConfigurationResponse); }
	virtual	int DeleteDot1XConfiguration_(const char *endpoint, const char *soap_action, _tds__DeleteDot1XConfiguration *tds__DeleteDot1XConfiguration, _tds__DeleteDot1XConfigurationResponse *tds__DeleteDot1XConfigurationResponse);

	/// Web service operation 'GetDot11Capabilities' (returns error code or SOAP_OK)
	virtual	int GetDot11Capabilities_(_tds__GetDot11Capabilities *tds__GetDot11Capabilities, _tds__GetDot11CapabilitiesResponse *tds__GetDot11CapabilitiesResponse) { return this->GetDot11Capabilities_(NULL, NULL, tds__GetDot11Capabilities, tds__GetDot11CapabilitiesResponse); }
	virtual	int GetDot11Capabilities_(const char *endpoint, const char *soap_action, _tds__GetDot11Capabilities *tds__GetDot11Capabilities, _tds__GetDot11CapabilitiesResponse *tds__GetDot11CapabilitiesResponse);

	/// Web service operation 'GetDot11Status' (returns error code or SOAP_OK)
	virtual	int GetDot11Status_(_tds__GetDot11Status *tds__GetDot11Status, _tds__GetDot11StatusResponse *tds__GetDot11StatusResponse) { return this->GetDot11Status_(NULL, NULL, tds__GetDot11Status, tds__GetDot11StatusResponse); }
	virtual	int GetDot11Status_(const char *endpoint, const char *soap_action, _tds__GetDot11Status *tds__GetDot11Status, _tds__GetDot11StatusResponse *tds__GetDot11StatusResponse);

	/// Web service operation 'ScanAvailableDot11Networks' (returns error code or SOAP_OK)
	virtual	int ScanAvailableDot11Networks_(_tds__ScanAvailableDot11Networks *tds__ScanAvailableDot11Networks, _tds__ScanAvailableDot11NetworksResponse *tds__ScanAvailableDot11NetworksResponse) { return this->ScanAvailableDot11Networks_(NULL, NULL, tds__ScanAvailableDot11Networks, tds__ScanAvailableDot11NetworksResponse); }
	virtual	int ScanAvailableDot11Networks_(const char *endpoint, const char *soap_action, _tds__ScanAvailableDot11Networks *tds__ScanAvailableDot11Networks, _tds__ScanAvailableDot11NetworksResponse *tds__ScanAvailableDot11NetworksResponse);

	/// Web service operation 'GetSystemUris' (returns error code or SOAP_OK)
	virtual	int GetSystemUris_(_tds__GetSystemUris *tds__GetSystemUris, _tds__GetSystemUrisResponse *tds__GetSystemUrisResponse) { return this->GetSystemUris_(NULL, NULL, tds__GetSystemUris, tds__GetSystemUrisResponse); }
	virtual	int GetSystemUris_(const char *endpoint, const char *soap_action, _tds__GetSystemUris *tds__GetSystemUris, _tds__GetSystemUrisResponse *tds__GetSystemUrisResponse);

	/// Web service operation 'StartFirmwareUpgrade' (returns error code or SOAP_OK)
	virtual	int StartFirmwareUpgrade_(_tds__StartFirmwareUpgrade *tds__StartFirmwareUpgrade, _tds__StartFirmwareUpgradeResponse *tds__StartFirmwareUpgradeResponse) { return this->StartFirmwareUpgrade_(NULL, NULL, tds__StartFirmwareUpgrade, tds__StartFirmwareUpgradeResponse); }
	virtual	int StartFirmwareUpgrade_(const char *endpoint, const char *soap_action, _tds__StartFirmwareUpgrade *tds__StartFirmwareUpgrade, _tds__StartFirmwareUpgradeResponse *tds__StartFirmwareUpgradeResponse);

	/// Web service operation 'StartSystemRestore' (returns error code or SOAP_OK)
	virtual	int StartSystemRestore_(_tds__StartSystemRestore *tds__StartSystemRestore, _tds__StartSystemRestoreResponse *tds__StartSystemRestoreResponse) { return this->StartSystemRestore_(NULL, NULL, tds__StartSystemRestore, tds__StartSystemRestoreResponse); }
	virtual	int StartSystemRestore_(const char *endpoint, const char *soap_action, _tds__StartSystemRestore *tds__StartSystemRestore, _tds__StartSystemRestoreResponse *tds__StartSystemRestoreResponse);
};
#endif
