/* soapwsddService.h
   Generated by gSOAP 2.8.17r from onvif.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapwsddService_H
#define soapwsddService_H
#include "soapH.h"
class SOAP_CMAC wsddService : public soap
{ public:
	/// Constructor
	wsddService();
	/// Construct from another engine state
	wsddService(const struct soap&);
	/// Constructor with engine input+output mode control
	wsddService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	wsddService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~wsddService();
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to defaults
	virtual	void reset();
	/// Initializer used by constructor
	virtual	void wsddService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	wsddService *copy() SOAP_PURE_VIRTUAL;
	/// Close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(struct _wsse__Security *wsse__Security, char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Then accept SSL handshake, when SSL is used
	virtual	int ssl_accept();
#endif
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service one-way operation 'Hello' (return error code, SOAP_OK (no response), or send_Hello_empty_response())
	virtual	int Hello(struct wsdd__HelloType *wsdd__Hello) SOAP_PURE_VIRTUAL;
	virtual	int send_Hello_empty_response(int httpcode) { return soap_send_empty_response(this, httpcode); }

	/// Web service one-way operation 'Bye' (return error code, SOAP_OK (no response), or send_Bye_empty_response())
	virtual	int Bye(struct wsdd__ByeType *wsdd__Bye) SOAP_PURE_VIRTUAL;
	virtual	int send_Bye_empty_response(int httpcode) { return soap_send_empty_response(this, httpcode); }

	/// Web service one-way operation 'Probe' (return error code, SOAP_OK (no response), or send_Probe_empty_response())
	virtual	int Probe(struct wsdd__ProbeType *wsdd__Probe) SOAP_PURE_VIRTUAL;
	virtual	int send_Probe_empty_response(int httpcode) { return soap_send_empty_response(this, httpcode); }

	/// Web service one-way operation 'ProbeMatches' (return error code, SOAP_OK (no response), or send_ProbeMatches_empty_response())
	virtual	int ProbeMatches(struct wsdd__ProbeMatchesType *wsdd__ProbeMatches) SOAP_PURE_VIRTUAL;
	virtual	int send_ProbeMatches_empty_response(int httpcode) { return soap_send_empty_response(this, httpcode); }

	/// Web service one-way operation 'Resolve' (return error code, SOAP_OK (no response), or send_Resolve_empty_response())
	virtual	int Resolve(struct wsdd__ResolveType *wsdd__Resolve) SOAP_PURE_VIRTUAL;
	virtual	int send_Resolve_empty_response(int httpcode) { return soap_send_empty_response(this, httpcode); }

	/// Web service one-way operation 'ResolveMatches' (return error code, SOAP_OK (no response), or send_ResolveMatches_empty_response())
	virtual	int ResolveMatches(struct wsdd__ResolveMatchesType *wsdd__ResolveMatches) SOAP_PURE_VIRTUAL;
	virtual	int send_ResolveMatches_empty_response(int httpcode) { return soap_send_empty_response(this, httpcode); }
};
#endif
